- csmnet/src/CPP/endpoint_ptp.cc
this fix will prevent the simple "disconnect because of bad msg" and turns it into "first expected msg needs to be version msg for verification".
I tested with CAST 1.0.0 daemon which gets rejected and exits with the version mismatch error.
> fix for issue #21

- csmd/src/pamd/src/csm_pam.cc
> Removing old debug printf.

- csmi/src/wm/cmd/allocation_create.c
> Added launch_node_name argument to csm_allocation_create commandline.

- csmnet/src/CPP/reliable_msg.cc
This should fix the crash.
However, I have not been able to recreate.It could be hard to reproduce. See comment in issue #65
> candidate fix for #65

- bb/tests/keywords_lsf.robot
- bb/tests/keywords_toolbox.robot
- bb/tests/lsf/basic.robot
Fix test cases for user scripts specified for phase 1 or 2 specified but do not exist (dne)
> Fix user stageout1/2 does not exist test cases

- csmd/src/daemon/src/csmi_request_handler/CSMIAllocationCreate.cc
- csmd/src/daemon/src/csmi_request_handler/CSMIAllocationStepBegin.cc
- csmd/src/daemon/src/csmi_request_handler/CSMIAllocationStepEnd.cc
- csmdb/sql/csm_create_triggers.sql
- csmdb/sql/csm_drop_functions.sql
- csmi/include/csm_types/struct_defs/wm/csmi_allocation_step_mcast_context.def
- csmi/include/struct_generator/generate_struct.pl
- csmi/src/bb/src/csmi_bb_internal.c
- csmi/src/common/include/csmi_struct_hash.h
- csmi/src/common/src/csmi_json.cc
- csmi/src/common/src/csmi_struct_hash.c
- csmi/src/diag/src/csmi_diag_internal.c
- csmi/src/inv/src/csmi_inv_internal.c
- csmi/src/ras/src/csmi_ras_internal.c
- csmi/src/wm/include/csmi_wm_type_internal.h
- csmi/src/wm/src/csmi_wm_internal.c
Added a transaction log for the step transactions. Fixes a bug in the json generator in C++.
> Feature step transaction

- csmdb/sql/CMakeLists.txt
correction made to cmake file.
> cmake - missing ) correction

- csmd/src/daemon/src/csmi_request_handler/CSMIAllocationAgentUpdateState.cc
- csmd/src/daemon/src/csmi_request_handler/helpers/cgroup.cc
Added an improved error logger for the allocation create/delete, implemented a linear back off for cgroup task kills.
> Allocation error enhancements

- csmd/src/daemon/src/csmi_request_handler/CSMIAllocationStepBegin.cc
- csmd/src/daemon/src/csmi_request_handler/CSMIAllocationStepBegin.h
- csmd/src/daemon/src/csmi_request_handler/CSMIAllocationStepEnd.cc
- csmd/src/daemon/src/csmi_request_handler/CSMIAllocationStepEnd.h
Added the private check functions.
> Improved the step begin and end apis for user auth.

- csmtest/buckets/advanced/allocation.sh
Issue #92 
Bucket is same as described in that thread, with 3 intermittent checks of `csm_allocation_query_active_all` output for quality control
> CSM FVT test cases for creating allocations on a node with active staging-out allocations

- csm_big_data/elasticsearch/mappings/templates/cast-allocation.json
> Added a cast-allocation prototype to handle timestamps.

- bb/src/LVUtils.cc
- bb/src/xfer.cc
> bb:Use bfs::copy_option::overwrite_if_exists for local/remote copy

- bb/src/BBTagInfoMap2.cc
- bb/src/BBTagInfoMap2.h
- bb/src/bbserver.cc
- bb/src/bbwrkqmgr.cc
- bb/src/xfer.cc
- bb/src/xfer.h
> Improve system integrity

- bb/wrappers/Procedures.py
- bb/wrappers/bb.py
> bb:Wrapper changes

- bb/src/BBTagInfo2.cc
- bb/src/bbserver.cc
- bb/src/connections.cc
- utilities/src/util.cc
> bb:Additional console logging for uuid information for LVs and files

- csmdb/sql/csm_db_connections_script.sh
- csmdb/sql/csm_db_script.sh
- csmdb/sql/csm_db_stats.sh
> csmdb fixed log path

- csmdb/sql/csm_db_connections_script.sh
- csmdb/sql/csm_db_script.sh
- csmdb/sql/csm_db_stats.sh
> another fix

- csmd/src/daemon/include/csm_event_routing.h
- csmd/src/daemon/src/CMakeLists.txt
- csmd/src/daemon/src/csm_event_routing_master.cc
- csmd/src/daemon/src/csmi_request_handler/CSMINodeFindJob.cc
- csmd/src/daemon/src/csmi_request_handler/CSMINodeFindJob.h
- csmi/include/csm_api_inventory.h
- csmi/include/csm_types/struct_defs/inv/csm_node_find_job_input.def
- csmi/include/csm_types/struct_defs/inv/csm_node_find_job_output.def
- csmi/include/csm_types/struct_defs/inv/csmi_node_find_job_record.def
- csmi/include/csm_types/struct_defs/inv/type_order.def
- csmi/include/csmi_type_inv.h
- csmi/include/csmi_type_inv_funct.h
- csmi/src/common/include/csmi_cmds_def.h
- csmi/src/inv/cmd/CMakeLists.txt
- csmi/src/inv/cmd/node_find_job.c
- csmi/src/inv/include/csmi_inv_internal.h
- csmi/src/inv/src/csmi_inv_internal.c
- csmi/src/inv/src/csmi_inv_python.cc
- csmi/src/inv/src/csmi_inv_serialization.c
- csmi/src/inv/src/csmi_node_find_job.c
This is a new CSM API to help find a job that ran (or is running) on a node during a specific time frame. 
The API has been partially implemented, but at this point in time a user can input a `node_name` along with a time range. Then the results will display any job records that ran on that node during that time frame. 
- This API has more flags and options for search that has not been implemented yet. But basic functionality addressing the original issue has been completed. I am pushing this code so others on the team can run this in development code to meet the base needs earlier than a full release and also so that the test team can get an early head start developing tests against this new code. 
1. Set up a cluster.
2. Create some allocations.
3. Run this API. while: a.) select node …
> Feature new/csm node find job

- bb/scripts/bbtools.pm
- bb/src/bbcmd.cc
* Improve bbcmd tracing
2. Test it.
> Fix LSF_STAGE_HOSTS and LSB_HOSTS processing for default hostlist

- bb/scripts/bbtools.pm
- bb/src/bbcmd.cc
> Revert LSF_STAGE_HOSTS launch node removal change

- .github/CODEOWNERS
- filled in to best of my knowledge
- others should contribute to this file if they want ownership over a part of code. This will auto add them in as reviewers as we improve automation of github features. 
1. See if this automation works when new pull requests are opened.
> filled in more of CODEOWNERS File

- bb/scripts/bbactivate.pl
- bb/src/bbcmd.cc
- bb/src/nodecontroller.cc
- bb/src/nodecontroller.h
- bb/src/nodecontroller_csm.cc
- bb/src/nodecontroller_csm.h
> Improvements to bbcmd and login/launch node setup

- bb/scripts/bbactivate.pl
- bb/scripts/postinstall.sh
* new option to specify bscfswork
* improved RPM install for genimage
> BB installation and setup improvements

- csmd/src/daemon/include/csm_event_sink_set.h
- csmd/src/daemon/src/connection_handling.cc
- csmd/src/daemon/src/csm_daemon_config.cc
- csmd/src/daemon/src/csm_daemon_core.cc
- csmd/src/daemon/src/csm_event_sink_set.cc
- csmnet/src/CPP/csm_version_msg.h
- csmnet/src/CPP/multi_endpoint.cc
Small cleanup, primarily during daemon shutdown
Cleans up some memleaks found via valgrind.
> some small cleanup

- bb/scripts/bbhealth.pl
Use syslog module for critical bbhealth messages.  General script formatting cleanup.
> Add syslog support to bbhealth; improve debug output

- export_layout.c
Version update to 1.3.  Do dmesg for map_blocks rc nonzero.
> Do a printk for return code from mapblocks.

- bb/src/bbwrkqmgr.cc
> bb: Additional clarification for work queue manager dump titles

- bb/wrappers/Procedures.py
- bb/wrappers/bbapi_main.py
> bb: Add wrapper procedure for GetTransferInfo

- bb/scripts/bbactivate.pl
If the compute node is configured with a swap file using the BB volume group, bbactivate will fail.  This swap LV is not mounted and bbactivate was attempting to clean it up.  This patch skips the cleanup if the LV is being used for swap.
> Do not remove logical volume in BB volume group if it is used by swap

- csmdb/sql/csm_history_table_archive_template.sh
- csmdb/sql/csm_ras_event_action_table_archive.sh
One line fix for the json parsing. Added sed to escape the control characters.
> Fixed the archive for json parsing.

- csmd/src/daemon/src/csmi_request_handler/CSMIJSRUNCMD.cc
- csmd/src/daemon/src/csmi_request_handler/CSMIJSRUNCMDAgentState.cc
- csmd/src/daemon/src/csmi_request_handler/helpers/Agent.cc
- csmi/src/CMakeLists.txt
Python shared objects were not being built properly, new fix allows them to be built and places them in the api RPM.
> Fixed python library build

- csmd/src/daemon/src/csmi_request_handler/CSMIJSRUNCMD.cc
- csmd/src/daemon/src/csmi_request_handler/CSMIJSRUNCMDAgentState.cc
- csmd/src/daemon/src/csmi_request_handler/helpers/Agent.cc
Added trace logging around the execv call.
> Added improved trace logging for csm_launch

- bb/src/ContribIdFile.cc
> bb: Fix error in new static ContribIdFile::isStopped()

- bb/src/bbcmd.cc
Removing test commands related to bringup of failover.
> Clean up bbcmd test functions

- bb/src/BBLV_Info.cc
- bb/src/BBTransferDef.cc
- bb/src/LVUtils.cc
- bb/src/bbapi.cc
- bb/src/bbserver.cc
- bb/src/bbwrkqe.cc
- bb/src/bbwrkqmgr.cc
- bb/src/xfer.cc
> bb:TODO/FIXME comment changes

- csmd/src/daemon/src/csmi_request_handler/CSMIJSRUNCMDAgentState.cc
- csmd/src/daemon/src/csmi_request_handler/helpers/Agent.cc
- csmd/src/daemon/src/csmi_request_handler/helpers/cgroup.cc
Added additional trace level logging for the jsrun execution for debugging issues.
Added a reset to the attempt counter for waiting on pid migration in the execution code.
> csm_jsrun improvements.

- bb/scripts/bbactivate.pl
- bb/scripts/bbactivate.pod
- bb/scripts/bbtools.pm
- bb/scripts/stagein_admin.pl
- bb/scripts/stageout_admin.pl
* Add options --dryrun and --drypath
* Add various timeouts to bb.cfg
- stagein user script timeout
- stageout1 user script timeout
- stageout2 user script timeout
- transfer wait timeout
* General code cleanup / tidy
> Improvements to bbactivate and staging scripts

- csmd/src/ras/bmc/CSMpolicyTable.json
- csmd/src/ras/bmc/p9_witherspoon_csm_ras_type_data.csv
- csmdb/sql/csm_ras_type_data.csv
This pull request contains updates to the CSM RAS msg type csv file based on changes contained in the ibm-crassd-0.8-15 policy table.
> CSM RAS: update BMC ras msg types based on ibm-crassd-0.8-15

- bb/wrappers/bbapi_main.py
> bb: Minor wrapper change

- bb/scripts/CMakeLists.txt
- bb/scripts/bbcfg.pod
This creates the man page for bb.cfg.  More editing will be necessary.
> Create bb.cfg man page

- bb/src/LVUtils.cc
- bb/src/bbproxy.cc
- bb/src/bbserver.cc
- bb/src/nodecontroller.cc
- bb/src/nodecontroller_csm.cc
- bb/src/xfer.cc
- bb/wrappers/bbapiAdmin.py
- csm_big_data/beats/config/filebeat.yml
- csmd/src/daemon/src/csm_bds_manager.cc
- csmd/src/inv/ib_and_switch/src/standalone_ib_and_switch_collection.cc
- csmdb/sql/CMakeLists.txt
- csmdb/sql/csm_create_tables.sql
- csmdb/sql/csm_db_clear_archive_time.sh
- csmdb/sql/csm_db_history_archive.sh
- csmdb/sql/csm_db_utils.sh
- csmdb/sql/csm_history_table_archive_template.sh
- csmdb/sql/csm_history_wrapper_archive_script_template.sh
- csmdb/sql/csm_history_wrapper_delete_script_template.sh
- csmdb/sql/csm_ras_event_action_table_archive.sh
- csmdb/sql/csm_ras_event_action_wrapper_archive_script.sh
- csmnet/src/CPP/endpoint_ptp.h
- docs/source/cast-big-data/python-guide.rst
- docs/source/index.rst
Added new instrumentation to the archive scripts.
> Archive script instrumentation enhancements

- csmdb/sql/csm_create_triggers.sql
`err_text` now has a more verbose value for allocation removed steps.
> Adding improved debugging for issue #312

- csmutil/csm_log_utility/CMakeLists.txt
- csmutil/csm_log_utility/Helper_Files/CMakeLists.txt
- csmutil/csm_log_utility/Logs/CMakeLists.txt
- csmutil/csm_log_utility/Reports/CMakeLists.txt
#ship API logging tools src into RPM
to get the ball rolling on including the expected upgrades. this way we move towards continuous development and integration. new features and upgrades to follow. 
- working on : https://github.com/IBM/CAST/issues/310
- adds to the csm-core
- tested and works.
- I ran the logging tools from this location and saw expected results.
ToDo:
1. install rpm
2. look for new directories
3. run logging tools
4. see logging results
> ship API logging tools src into RPM

- csm_big_data/python/cast_helper.py
- csm_big_data/python/findJobKeys.py
- csm_big_data/python/findJobMetrics.py
- csm_big_data/python/findJobsInRange.py
- csm_big_data/python/findJobsRunning.py
Switched use cases from using human readable times to epoch time.
> Fixes for big data use cases

- csmd/src/daemon/src/csm_environmental_data.cc
Added a regex cleanup to `GetJsonString` to properly format the JSON so it's compliant with the JSON standard for numbers.
> Numeric types are now JSON compliant for environmental collection.

- csm_big_data/python/findJobKeys.py
- csm_big_data/python/findJobsInRange.py
- csm_big_data/python/findJobsRunning.py
- csm_big_data/python/findUserJobs.py
- docs/source/cast-big-data/elasticsearch.rst
- docs/source/cast-big-data/index.rst
- docs/source/cast-big-data/python-guide.rst
A collection of minor textual changes to the use case help functions and read the docs.
> Cleanup of usecases and install guide.

- csmd/src/daemon/src/csm_environmental_data.cc
Updates to the regular expression to capture negative numbers and reject numbers with leading zeroes.
> Environment JSON fixes

- csm_big_data/elasticsearch/mappings/templates/cast-allocation.json
- csm_big_data/elasticsearch/mappings/templates/cast-counters-gpfs.json
- csm_big_data/elasticsearch/mappings/templates/cast-counters-ufm.json
- csm_big_data/elasticsearch/mappings/templates/cast-csm-dimm-env.json
- csm_big_data/elasticsearch/mappings/templates/cast-csm-gpu-counters.json
- csm_big_data/elasticsearch/mappings/templates/cast-csm-gpu-env.json
- csm_big_data/elasticsearch/mappings/templates/cast-csm-node-env.json
- csm_big_data/elasticsearch/mappings/templates/cast-csm-processor-env.json
- csm_big_data/elasticsearch/mappings/templates/cast-db-csm.json
- csm_big_data/elasticsearch/mappings/templates/cast-log-console.json
- csm_big_data/elasticsearch/mappings/templates/cast.json
- csm_big_data/python/findWeightedErrors.py
- csm_big_data/python/sampleWeightedErrorMap.json
- docs/source/cast-big-data/csm-event-correlator.rst
- docs/source/cast-big-data/kibana.rst
- docs/source/cast-big-data/logstash.rst
- docs/source/csmdb/csm_db_stats_sh.rst
Improvements to the documentation and fixed some bugs caught by @fpizzano.
> Documentation enhancements and usecase bug fixes.

- bb/src/bbproxy.cc
- bb/src/bbserver.cc
- bb/src/serial.cc
Add try-catch blocks in serial.cc
> Issue993 trycatch

- bb/src/fh.cc
> bb: Fix SIGSEGV introduced by pull request #363

- bb/tests/keywords_toolbox.robot
- bb/tests/resiliency/setserver.robot
Add testcases for double failover with transfers initiated to different servers.
> Add resiliency testcases

- docs/source/csmd/csm_daemon.rst
> csm: extended csmd docs

- bb/wrappers/Procedures.py
- bb/wrappers/RunProcedure.py
- bb/wrappers/bb.py
- bb/wrappers/bbapiAdmin.py
- bb/wrappers/bbapiAdminProcs.py
- bb/wrappers/bbapi_main.py
> bb: Wrapper changes for improved testing

- bb/src/BBTransferDef.cc
- bb/src/bberror.cc
- bb/src/bberror.h
> bb: When clearing bberror, preserve the ok2Clear attribute

- bb/src/nodecontroller_csm.cc
Provide more information on return codes from csm when bb calls csm interfaces.
> Bb show csm rc

- bb/scripts/bbhealth.pl
- bb/scripts/bbtools.pm
Remove excessive "connection appears to be up" log messages in bbhealth.  Display debug information when getting malformed json.
> Improve logging

- csmi/src/inv/cmd/node_attributes_query.c
- working on https://github.com/NickyDaB/CAST/issues/25
> update help to include suggestion for HARD_FAILURE

- csmconf/csm_master.cfg
- csmd/src/inv/ib_and_switch/src/CMakeLists.txt
- csmd/src/inv/ib_and_switch/src/example_ssl.txt
- csmd/src/inv/ib_and_switch/src/standalone_ib_and_switch_collection.cc
- remove username and password from `csm_master.cfg`
- fields replaced with paths to a SSL file containing a key
- makes program a little more secure. 
- labs to create an SSL key and store it in a file for CSM to parse
- I did basic functionality testing and it works. 
- ToDo: update ufm inventory collection to support new workflow.
> Ssl config upgrade

- csmtest/buckets/basic/inventory_collection.sh
- csmtest/buckets/error_injection/allocation.sh
- csmtest/config.template
- csmtest/include/prologs/privileged_epilog
- csmtest/include/prologs/privileged_epilog_generic
- csmtest/include/prologs/privileged_epilog_timeout
- csmtest/include/prologs/privileged_prolog
- csmtest/include/prologs/privileged_prolog_255
- csmtest/include/prologs/privileged_prolog_generic
- csmtest/include/prologs/privileged_prolog_timeout
- csmtest/setup/csm_install.sh
General improvements to FVT for CSM 1.4.0.  Specifically includes fixes/enhancements for
1. SSL key mechanism for inventory collection #410 
2. CSM allocation timeout and permissions error paths #382
> CSM FVT Improvements

- csmd/src/daemon/src/csmi_request_handler/CSMIAllocationCreate.cc
- csmd/src/daemon/src/csmi_request_handler/CSMIJSRUNCMD.cc
- csmd/src/daemon/src/csmi_request_handler/CSMIJSRUNCMDAgentState.cc
- csmd/src/daemon/src/csmi_request_handler/CSMISoftFailureRecovery.cc
- csmd/src/daemon/src/csmi_request_handler/csm_interval_handler.cc
- csmd/src/daemon/src/csmi_request_handler/csmi_db_resp_state.h
- csmd/src/daemon/src/csmi_request_handler/csmi_handler_state.cc
- csmd/src/daemon/src/csmi_request_handler/csmi_mcast/CSMIMcastAllocation.cc
- csmd/src/daemon/src/csmi_request_handler/csmi_mcast/CSMIMcastJSRUN.cc
- csmd/src/daemon/src/csmi_request_handler/csmi_mcast/CSMIMcastJSRUN.h
- csmd/src/daemon/src/csmi_request_handler/csmi_mcast/CSMIMcastSoftFailureRecovery.h
- csmd/src/daemon/src/csmi_request_handler/helpers/Agent.h
- csmd/src/daemon/src/csmi_request_handler/helpers/EventHelpers.h
- csmi/include/csm_types/struct_defs/wm/csm_soft_failure_recovery_input.def
- csmi/include/csm_types/struct_defs/wm/csmi_jsrun_cmd_payload.def
- csmi/include/csmi_type_wm.h
- csmi/src/wm/cmd/soft_failure_recovery.c
- csmi/src/wm/include/csmi_wm_type_internal.h
- csmi/src/wm/src/csmi_soft_failure_recovery.c
- csmi/src/wm/src/csmi_wm_internal.c
- csmi/src/wm/src/csmi_wm_python.cc
Added new enhancements to the soft failure recovery API, added type to jsrun_cmd, fixed memory leak in allocation_create.
> Soft failure enhancement

- bb/scripts/bbactivate.pl
- bb/scripts/bbhealth.pl
- utilities/src/identity.cc
Backup server calculation during bbactivate was not handling multiple racks
Add bbProxy restart after 5 failed start attempts
User cache handling newly added userids after previous failed attempts.
> Various fixes for failover

- docs/source/csmdb/csm_db_appendix.rst
csmdb_update: pdf and image testing
to upload images and or pdf files to the repo.
> csmdb_update: pdf and image testing

- csm_big_data/beats/config/filebeat.yml
- docs/source/cast-big-data/cast-search.rst
- docs/source/cast-big-data/data-aggregators.rst
- docs/source/cast-big-data/index.rst
- docs/source/cast-big-data/kibana.rst
- docs/source/conf.py
- docs/source/csm/index.rst
- docs/source/csm/soft_failure.rst
- docs/source/csmd/csm_daemon.rst
Working on adding new documentation for the filebeat changes and CAST Search. This is a primary trial of images for Read the Docs, images are hosted in a [forked repo issue](https://github.com/mew2057/CAST/issues/3).
@williammorrison2 This is my new mechanism for images.
@morrone This PR adds some documentation for the CAST Search utility ( docs/source/cast-big-data/cast-search.rst )
> Documentation enhancements

- bb/src/bbproxy.cc
- bb/src/bbserver.cc
- bb/src/connections.cc
Ensure bbproxy is initialized before it will allow bbcmd/bbapi to connect.  
Ensure bbserver is initialized before it will allow bbproxy to connect.
> Notreadyforbbcmd

- csm_big_data/data-aggregators/gpfs/zimonCollector.py
- csm_big_data/data-aggregators/ufm/ufmCollection.py
- csm_big_data/python/cast_helper.py
- csm_big_data/python/findJobKeys.py
- csm_big_data/python/findJobMetrics.py
- csm_big_data/python/findJobTimeRange.py
- csm_big_data/python/findJobsInRange.py
- csm_big_data/python/findJobsRunning.py
- csm_big_data/python/findUserJobs.py
- csm_big_data/python/findWeightedErrors.py
Fixes for the miscellaneous issues in use cases. Please refer to commits for issues modified.
> Data Aggregator Fixes

- csmtest/buckets/basic/soft_failure_recovery.sh
- csmtest/buckets/error_injection/allocation.sh
- csmtest/tools/complete_fvt.sh
Related Issues/PRs:
#432 #421 #389 
Summary:
1. Creation of csm_soft_failure_recovery basic regression bucket
2. Minor fixes to csm_allocation_create/delete prolog/erpilog error injections
> CSM FVT Improvements for 1..4.0

- bb/scripts/bbactivate.pl
- bb/src/BBTransferDef.cc
Also minor log message typo fix
> Fix flag to enable CSM on launch nodes

- docs/source/csmd/csmd_config.rst
note about the heartbeat taken from the previous documentation.
> add documentation note about csm heartbeat

- bb/scripts/genbbcfg.pl
- bb/src/gendefaults.pl
- bb/src/tracksyscall.cc
- scripts/configure.pl
cmake3 support
Incorrect flightlog header used during bbProxy build
Build hang when $USER is not defined.
> Various build fixes

- bb/src/connections.cc
- transport/include/CnxSockSSL.h
- transport/include/Connex.h
Improve burst buffer problem solving involving bbserver by providing IP address in the bbproxy naming
> Namethatbbproxy

- bb/src/bbcmd.cc
- bb/src/bberror.h
- bb/src/main.cc
- bb/tools/comparefiles.cc
- bb/tools/randfile.cc
- bb/tools/removefiles.cc
- utilities/src/logging.cc
Largely better handling of rare exceptions during init phases.
> More fixes for various issues identified by static analysis

- csm_big_data/rpmscripts/kibana.post.install
- csm_big_data/rpmscripts/kibana.post.uninstall
- csm_big_data/rpmscripts/kibana.pre.uninstall
- csm_big_data/rpmscripts/logstash.post.install
- csm_big_data/rpmscripts/logstash.post.uninstall
- csm_big_data/rpmscripts/logstash.pre.uninstall
- csm_big_data/setupRPM.cmake
- csmi/src/wm/cmd/allocation_query_details.c
- docs/source/cast-big-data/data-aggregators.rst
- utilities/src/logging.cc
A collection of minor bug fixes:
- Issue #473: All fields are now printed.
- Issue #472: Scriptlets are now pre.uninstall; removed if statements.
- Issue #471: Added pid and process to syslog.
> 1.4.0 minor bugfixes

- docs/source/csm-integration/Mellanox_and_Infiniband.rst
- docs/source/csm-integration/index.rst
- docs/source/index.rst
working on : https://github.com/NickyDaB/CAST/issues/31
document how to connect to UFM restfulAPIs via SSL connection
> how to create SSL key

- bb/src/nodecontroller_csm.cc
Workaround for csm_allocation_query DB issues
> Query allocation using csm_allocation_query_active_all instead

- bb/src/bbcmd.cc
- csmd/src/daemon/src/csmi_request_handler/helpers/Agent.cc
+ minor logging change in bbcmd
> Fix backward test in csmd/Agent.cc impacting csm_bb_cmd()

- bb/src/bbwrkqmgr.cc
- bb/src/tracksyscall.cc
- bb/src/tracksyscall.h
> bb:Monitor the syscalls for the async request file I/O

- bb/src/bbwrkqmgr.cc
> bb:Add flight logging for the async request file I/O

- csm_big_data/beats/config/filebeat.yml
- csmconf/csm_master.cfg
- csmi/src/common/include/csmi_struct_hash.h
- csmi/src/common/src/csmi_json.cc
- utilities/src/logging.cc
Fixed JSON generation for transaction log:
Issue #498 
Issue #502
Fixed transaction log rotation and filebeats implementation:
Issue #507
> Fixes to the CSM logs

- csmtest/buckets/basic/db_connections_script.sh
- csmtest/buckets/basic/db_ras_type_script.sh
- csmtest/buckets/basic/db_stats_script.sh
- csmtest/include/sql/csm_ras_type_data_test_1.csv
- csmtest/include/sql/csm_ras_type_data_test_2.csv
- csmtest/include/sql/csm_ras_type_data_test_3.csv
csm DB basic test bucket scripts
Automated process that tests the functionality of CSM DB utility scripts which include:
__**csm_db_connections_script.sh**__
* listing DB connections
* listing specific user connections
* killing connections related to user and or PID
__**csm_db_stats.sh**__
* testing all the command line arguments
__**csm_db_ras_type_script.sh**__
Each command line argument is covered along with other options including:
* prompt messages "y/n" (if applicable)
* importing of test data to specific RAS tables - updating records and or importing new message types.
* removing RAS table data (if necessary) 
__**Pre-Merge TODOs**__
__**How to Test**__
1. Run Regression (Include in our current test environment)
> csm DB basic test bucket scripts

- csmdb/sql/csm_create_tables.sql
- csmdb/sql/csm_create_triggers.sql
- csmdb/sql/csm_db_schema_version_data.csv
- csmdb/sql/csm_delete_data.sql
- csmdb/sql/csm_drop_functions.sql
- csmdb/sql/csm_drop_tables.sql
csm_db_initial_upgrade_to_17.0
Continued Development for 1.5.0 release
Run regression to ensure the new
> csm_db_initial_upgrade_to_17.0

- README.md
I was trying to find what CAST stands for and found it on the Contributing.md page, but nothing on the landing README for the GitHub project, felt we should add it there.  
Simple change to the README 
You can see the what it looks like at:  https://github.com/whowutwut/CAST/blob/readme_improv/README.md
> Add the meaning of CAST into the landing README page

- bb/src/connections.cc
- bb/src/connections.h
Accessor functions to version property tree.
> Accessor to version property tree

- csmd/src/daemon/src/csmi_request_handler/CSMIBBLVDelete.cc
- csmdb/sql/csm_create_tables.sql
- csmdb/sql/csm_create_triggers.sql
- csmdb/sql/csm_drop_functions.sql
- csmi/include/csm_types/struct_defs/bb/csm_bb_lv_delete_input.def
- csmi/include/csm_types/struct_defs/bb/type_order.def
- csmi/include/csmi_type_bb.h
- csmi/src/bb/cmd/bb_lv_delete.c
- csmi/src/bb/src/csmi_bb_internal.c
- csmi/src/bb/src/csmi_bb_python.cc
csmdb update related to the csm_lv_history table
added fields: num_reads, num_writes
> Bills db updates for 17 0

- csmconf/csm_api.cfg
- csmd/src/daemon/src/csmi_request_handler/helpers/cgroup.cc
Performed a redesign of how IRQBalance is set. Now modeled after a known good bash script.
`irqbalance` daemon interaction has been disabled as it kills CSM silently.
> Reimplemented the IRQBalance mechanism.

- bb/scripts/stagein_admin.pl
- bb/scripts/stageout_admin.pl
Transfer fails, but stage-in reports success and job proceeds #1006
> Fix staging pl to report transfer failure for stage in/out

- csmd/src/daemon/src/csm_event_source_set.cc
After a question from @besawn about the trace output of csmd, I reviewed the event source scheduling and found a minor issue that would cause the first entry in the list of sources to get scheduled twice per scheduling window.
Difference only noticable when enabling trace level logging for csmd and looking for "Scheduling Event Source" lines. Without the fix, one of the IDs will appear twice in a row in some cases.
> csm: improved event source scheduling

- csmtest/buckets/basic/pamd.sh
- csmtest/include/functions.sh
Some clean up on pamd bucket
#523
> CSM FVT: minor fixes to pamd basic bucket

- csmd/setupRPM.cmake
Relaxed ibm-csm-core version dependency on nvme-cli. 
Added ibm-csm-db dependency on pv rpm.
> Relaxed ibm-csm-core version dependency on nvme-cli. Added ibm-csm-db dependency on pv rpm.

- csmd/src/daemon/src/csmi_request_handler/helpers/Agent.cc
- csmd/src/daemon/src/csmi_request_handler/helpers/cgroup.cc
Reordering the IRQ affinity setting logic.
> IRQ reorder.

- csmd/src/daemon/src/csmi_request_handler/helpers/cgroup.cc
Increase of trace level in response to issue #575.
> Increasing trace fidelity of cgroup code.

- csmdb/sql/csm_create_triggers.sql
Power cap hit should now show zero when the power cap doesn't change.
> Added a fix to handle no change data metrics.

- csmtest/buckets/advanced/allocation.sh
- csmtest/buckets/basic/allocation.sh
- csmtest/buckets/error_injection/infrastructure.sh
Work in progress, not ready for merge
Tracking via #584
> CSM FVT Improvements for 1.5.0

- csmd/src/daemon/src/csmi_request_handler/helpers/cgroup.cc
The CSM per CPU usage accounting was only summarizing data correctly when SMT mode was set to 4.
I first noticed this problem when I observed that I was seeing data reported for 176 CPUs
in /var/log/ibm/csm/csm_allocation_metrics.log.0, when the maximum number of expected physical CPU cores
should have been 44.
Investigation revealed that the source of the problem was due to an erroronous calculation of the ratio
of logical to physical cores. Independent of SMT mode, the cgroup cpuacct.usage_percpu facility will
always report cpu usage for every possible logical cpu supported. The corrected code always uses the
same ratio of logical to physical cores when summarizing the usage per physical core; SMT mode is not
a factor in this calculation.
I ran a serious of tests comparing reported …
> Fixed issue with per CPU accounting for different SMT modes

- bb/scripts/bb_pre_exec.sh
- bb/scripts/stagein_admin.pl
burstbuffer not cleaning up after stage-in script failure #1016
> Userscriptstageinfailure

- csmdb/sql/csm_db_utility_setup_script.sh
> copyright fix 2019

- bb/src/BBLV_ExtentInfo.cc
- bb/src/BBLV_Info.cc
- bb/src/BBTagInfo.cc
- bb/src/BBTagInfo.h
- bb/src/BBTagInfoMap.cc
- bb/src/BBTagParts.cc
- bb/src/BBTransferDef.cc
- bb/src/BBTransferDef.h
- bb/src/ContribIdFile.cc
- bb/src/ContribIdFile.h
- bb/src/HandleFile.cc
- bb/src/HandleFile.h
- bb/src/LVUtils.cc
- bb/src/LVUtils.h
- bb/src/bbflags.h
- bb/src/bbinternal.h
- bb/src/bbproxy.cc
- bb/src/bbserver.cc
- bb/src/bbwrkqe.cc
- bb/src/bbwrkqmgr.cc
- bb/src/bbwrkqmgr.h
- bb/src/fh.cc
- bb/src/xfer.cc
- utilities/src/util.cc
> dev-dlherms Handle file lock protocol and many related items

- bb/src/LVUtils.cc
> bb:In isMounted(), fix pDevName length calculation

- bb/src/weak.cc
> Fix #601 override stat in boost leading to sigterm on logrotate

- csmd/src/daemon/include/item_scheduler.h
This PR changes the scheduling of environmental data collection from being based on daemon start time to being based on the beginning of the epoch (i.e. a common fixed point of time in the past).
Assuming synchronized time between compute nodes, this will help to collect the data of one configured bucket at the same time across the whole set of compute nodes.
Note that this is only addressing the synchronized data collection and will cause a burst of messages arriving at the service nodes and the BDS.
In my limited test environment, I could see the effect by looking at the time stamps of environmental data activity. I set the interval of a bucket to 15s and the events always were happening at offsets 00, 15, 30, and 45s regardless of the start time of the daemon. And I could only use the …
> synchronized environmental data collection

- csmdb/sql/csm_db_utility_setup_script.sh
Error handling exit status added.
> csmdb_update: added exit status 1 for error cases

- bb/src/BBTransferDef.cc
- bb/src/ContribIdFile.cc
- bb/src/HandleFile.cc
- bb/src/bbflags.h
> bb:Additional failover changes

- bb/src/BBTransferDef.cc
> bb:Coverity fix

- csmd/src/db/src/csm_db_event_content.cc
This is a bug fix for utf-8 bad byte pattern mitigation.
> UTF-8 Mitigation Strategy

- bb/scripts/stagein_admin.pl
- bb/src/connections.cc
- bb/src/serial.cc
Allow other names for host in config file.
> Allow other bb.cfg server names in bb.cfg

- csmd/src/inv/src/inv_dcgm_access.cc
CSM makes use of Data Center GPU Manager (DCGM) for most CSM functions related to GPU management. The first step in the process of interacting with DCGM is dynamically loading libdcgm.so. Packaging changes in datacenter-gpu-manager-1.5.6-1.ppc64le.rpm require CSM to load the library using the name libdcgm.so.1 instead.
Historically, previous version of datacenter-gpu-manager.rpm contain both libdcgm.so.1 and a symbolic link named libdcgm.so, which points to the current version of the library. CSM has always loaded the library using the name libdcgm.so rather than libdcgm.so.1. However, with the release of DCGM 1.5.6-1, the symbolic link is no longer included in the rpm, so CSM fails to find the library when attempting to load using the name libdcgm.so.
Package contents for DCGM 1.5.6-1: …
> Updated CSM dynamic loading of DCGM library due to DCGM 1.5.6-1 packaging changes

- csmdb/sql/csm_create_triggers.sql
> added parm to comment for function

- bb/src/BBLV_Info.cc
- bb/src/BBLV_Metadata.cc
- bb/src/BBTransferDef.cc
- bb/src/ContribIdFile.cc
- bb/src/ContribIdFile.h
- bb/src/xfer.cc
> bb:Additional restart changes related to handle file locking

- bb/src/weak.cc
Override __xstat (really. stat) to avoid boost exception in log rotate.
> Override __xstat weak symbol to avoid boost exception

- transport/src/Connex.cc
Report errno for read ssl socket fd failure.
> return errno on read socket fd

- csmd/src/daemon/src/csm_timer_manager.cc
set variable according to interrupted sleep status to prevent premature event trigger.
issue #658 was caused by missing variable assignment that was needed to restore a timer event after an interrupted sleep. This problem does not exist in 1.5 or earlier releases. It was introduced by commit 2905ab9 
This PR should fix the problem.
I also made some minor changes to reduce the number of system clock reads (in case logging was enabled).
Regarding testing to catch situations like that in the regression buckets:
- we'd need to find a way to interrupt currently active sleeps and confirm correct behavior
- one way could be to use the error_inject test tool: the test case for timeout testing uses a timer event and is therefore a candidate for testing.
1) request a timeout test with maybe 10s
2) …
> csm: fix for #658

- bb/src/bbGrabStderr.cc
- bb/src/bbGrabStderr.h
- bb/src/nodecontroller_csm.cc
Fixing coverity reported errors.
> Fix coverity discovered weaknesses on bbGrabStderr use

- bb/scripts/stagein_admin.pl
- bb/scripts/stageout_admin.pl
Use BSCFS_MNT_PATH variable rather than relying on LSB_SUB_ADDITIONAL.
> Change how bscfs is detected in start scripts

- csmdb/sql/csm_create_tables.sql
- csmdb/sql/csm_db_migration_scripts/csm_db_schema_updates_18_0_ms.sql
- csmdb/sql/csm_db_schema_version_upgrade_18_0.sh
- csmdb/sql/csm_drop_functions.sql
fix an issue related to #699 
1. Rerun some of the tests in the previous migration process.
2. Check the APIs to ensure we get no other DB constraint messages related to #699 .
> csmdb: migration 18.0 fixes

- csm_big_data/rpmscripts/kibana.pre.uninstall
- csm_big_data/rpmscripts/logstash.pre.uninstall
- csm_big_data/setupRPM.cmake
Scriptlet had malformed bash script. Fixed if statement.
> Repaired ibm-csm-bds-kibana pre.uninstall scriptlet

- csmd/src/inv/ib_and_switch/src/standalone_ib_and_switch_collection.cc
standardize guids accross csm
use the std function nate wrote
https://github.com/IBM/CAST/issues/697
look here for more details
> update to use standard guid for csm mellanox

- bb/src/bbwrkqe.cc
- bb/src/bbwrkqe.h
- bb/src/bbwrkqmgr.cc
- bb/src/xfer.cc
- bb/src/xfer.h
> bb:Additional transfer queue lock changes

- bb/src/bbwrkqe.cc
- bb/src/bbwrkqmgr.cc
> bb:Additional HP transfer queue lock changes

- bb/src/BBLV_Info.cc
- bb/src/BBTagInfo.cc
- bb/src/WorkID.h
- bb/src/bbserver.cc
- bb/src/bbwrkqe.cc
- bb/src/bbwrkqmgr.cc
> bb:Restart changes related to the changes in lock strategy

- bb/scripts/bb.cfg.in
- bb/src/bbwrkqmgr.cc
- bb/src/xfer.cc
> bb:Additional lock changes for restart processing

- bb/src/BBLV_Metadata.cc
- bb/src/xfer.cc
> bb: Additional restart changes

- csmtest/buckets/error_injection/timeout.sh
> csm_fvt: new case related to error inject timeout #658 #665

- csmtest/buckets/error_injection/allocation.sh
added test case regarding #759 and #760
Ran regression and the specific test case passes along with all other expected behavior.
> added test case regarding #759 and #760

- csmtest/buckets/advanced/allocation.sh
- csmtest/buckets/basic/allocation.sh
- csmtest/buckets/basic/bb.sh
- csmtest/buckets/basic/compute_node.sh
- csmtest/buckets/basic/db_script.sh
- csmtest/buckets/basic/hcdiag.sh
- csmtest/buckets/basic/ib_inventory.sh
- csmtest/buckets/basic/inventory_collection.sh
- csmtest/buckets/basic/jsrun_cmd.sh
- csmtest/buckets/basic/node.sh
- csmtest/buckets/basic/node_inventory_db_history.sh
- csmtest/buckets/basic/python_libraries.sh
- csmtest/buckets/basic/ras.sh
- csmtest/buckets/basic/soft_failure_recovery.sh
- csmtest/buckets/basic/step.sh
- csmtest/buckets/basic/switch_inventory.sh
- csmtest/buckets/error_injection/allocation.sh
- csmtest/buckets/error_injection/bb.sh
- csmtest/buckets/error_injection/infrastructure.sh
- csmtest/buckets/error_injection/messaging.sh
- csmtest/buckets/error_injection/node.sh
- csmtest/buckets/error_injection/versioning.sh
- csmtest/include/functions.sh
Modified the function to handle return code values in all test buckets (suggestion from a previous PR #767)
> fvt rc function advancements to test buckets

- bb/src/xfer.cc
> bb:Fix lock of local metadata if an exception is taken in stageoutEnd()

- csmd/src/daemon/include/csm_healthcheck_data.h
- csmd/src/daemon/src/csm_daemon_core_agent.cc
- csmd/src/inv/src/inv_aggregator_handler.cc
- csmi/src/common/src/csm_api_common.c
- csmi/src/common/src/csmi_common_utils.c
- csmnet/src/C/csm_network_local.c
PR contains a number of fixes for issues found by static analysis.
Mostly minor formatting, potential nullptr derefs of some code branches, corner cases, etc.
> static analysis fixes and repairs

- csmtest/include/hcdiag/clustconf.yaml
- csmtest/include/hcdiag/test.properties
csm_fvt hcdiag test bucket configuation changes to PASS regression
> csm_fvt hcdiag test bucket configuation changes to PASS regression

- bb/src/BBLV_ExtentInfo.cc
- bb/src/BBLV_Info.cc
- bb/src/BBLV_Metadata.cc
- bb/src/BBTagInfo.cc
- bb/src/BBTagInfoMap.cc
- bb/src/BBTagParts.cc
- bb/src/BBTransferDef.cc
- bb/src/bbwrkqe.cc
- bb/src/bbwrkqmgr.cc
- bb/src/bbwrkqmgr.h
> bb:Optimize dump() paths

- bb/src/connections.cc
regression tested against 
```/u/meaho/CAST/work/bb/tests/bin/initLoopSafety```
with loop 0-65535 of initLib then termLib repeated.
Fixed locking, end poller thread (responseThread) in termination.
> Fix sigsegv and hangs when looping initLib-termLib repeat

- bb/src/bbapi.cc
> bb:Revert to prior CRuntime check in BB_InitLibrary()

- bb/tools/scripts/analyze.py
- bb/tools/scripts/common.py
- bb/tools/scripts/processConsoleLogs.py
> bb:In tools/scripts, process stagein and stageout logs

- bb/src/BBTagInfoMap.cc
- bb/src/TagInfo.cc
- bb/src/TagInfo.h
- bb/src/bbserver.cc
> bb:Altered the fix for the getHandle race condition above

- bb/src/TagInfo.cc
> bb:Minor performance changes for getHandle

- csm_big_data/logstash/CMakeLists.txt
- docs/source/cast-big-data/common-problems.rst
- noticed the patch script wasnt in the /opt/folder
- no documentation for BDS upgrades
edited the cmake
- added documentation
> 1.7 updates

- bb/scripts/bbtools.pm
> Issue 1026:  poll for BBPATH data being ready

- bb/tests/resiliency/connect.robot
> Fix testcase to expect -2 return code from failure

- bb/tests/src/test_basic_xfer.c
* Add an optional command line argument that indicates if subdirectories
should be used in the PFS per node.
- Default: `0` (off - no subdirectories)
- Adding a `1` or `y` or `Y` as the fourth argument will enable
the use of subdirectories.
Add an optional command-line argument that indicates if subdirectories should be used in the PFS per node.
* Add an optional command-line argument that indicates if subdirectories
should be used in the PFS per node.
- Default: `0` (off - no subdirectories) - current behavior
- Adding a `1` or `y` or `Y` as the fourth argument will enable
the use of subdirectories.
Discussed enhancement offline with @tgooding 
Example run 4 processes-per-node without subdirectories (current behavior):
```
jsrun -r 4 test_basic_xfer  /pfspath/bb-testing $((4 * 1024 * …
```
> bb/tests: Add an option to use subdirectories in BB test

- utilities/src/util.cc
Now close files on bailout for ferror(f) nonzero (fix).
Malloc early on and avoid realloc in get line.  Free after the while loop and reuse the allocated storage.
In bailout for getline error, note the number of getline successes to understand more about getline failure.
> Always close file.  Simplify malloc/free for getline use.

- bb/src/HandleFile.cc
- bb/src/bbproxy.cc
- bb/src/bbserver.cc
> bb:Improve performance of getTransferInfo()

- bb/src/BBLV_Info.cc
> bb:Release metadata mutex around close() of target file

- scripts/rebuild
Copied logic from configure.pl
> Fix cmake version compare in rebuild script

- bb/src/fh.cc
- export_layout/src/export_layout.c
Changes to flag lease/close window.
> Export layout leases debug help

- export_layout/src/export_layout.c
Changed use of __DATE__ __TIME__ of export_layout build to be compiler compatible with RHEL7 and RHEL8 module build.
RHEL8 moved from iomap->blkno to iomap->addr for sector addressing.  Used #if kernel level checking to retain compatibility with RHEL7 install while fixing RHEL8 module build.
Here is a link to the iomap changing:  https://patchwork.kernel.org/patch/9927523/
@rosnbrg Could you also take a look at the change?  Thanks.
> RHEL8 changes for blkno to addr in iomap; RHEL7 compatible

- export_layout/src/export_layout.c
Another fix of DATE and TIME in module init
> Export layout r8

- docs/source/burst-buffer/bbinstall.rst
Document ansible playbooks for deploying and removing burstbuffer on a cluster.
> Document use of ibm burstbuffer ansible playbooks for deployment

- csmi/src/diag/cmd/diag_run_end.c
- csmi/src/diag/cmd/diag_run_query_details.c
- csmi/src/diag/src/csmi_diag_run_query_details.c
- csmi/src/wm/cmd/jsrun_cmd.c
noticed some additional init related issues once https://github.com/IBM/CAST/pull/914 brought the issue up. this pr addresses those additional issues. 
process and notes were documented internally here: https://github.ibm.com/CSM/team_process/issues/86
- https://github.ibm.com/CSM/team_process/issues/86
- https://github.com/IBM/CAST/pull/914 
- https://github.ibm.com/CSM/team_process/issues/80
- I ran the individual APIs. example screenshots can be seen in https://github.ibm.com/CSM/team_process/issues/86
- i would also recommend running csm regression on branch before merge
> Team process 86

- bb/src/HandleFile.cc
- bb/src/LVUtils.cc
- bb/src/bbwrkqmgr.cc
- bb/tools/comparefiles.cc
> Coverity changes, improved logging when metadata cannot be verified

- csmd/src/inv/src/inv_ssd_inventory.cc
This PR is a first pass at addressing https://github.com/IBM/CAST/issues/945. As progress is currently blocked in a customer environment, I implemented a quick and low risk fix for now. Long term it may be better to try to address this in a more future proof manner.
The root cause is a change in the path name that CSM is reading to determine the SSD size information between RHEL 7 and RHEL 8.
On RHEL 7, this information was retrieved from paths that looked like:
```
/sys/class/nvme/nvme0/nvme0n1/size
```
But on RHEL 8, these paths have changed to include some extra characters in the device name:
```
/sys/class/nvme/nvme0/nvme0c0n1/size
```
Note: this new name does not correspond to the device name reported by the `nvme-cli` utility:
```
Node             SN                   Model …
```
> CSM RHEL8: Updated CSM SSD inventory collection to look for the ssd size in a new location for RHEL 8 

- scripts/Dockerfile
Dockerfile for creating a container capable of building the CAST repository.
> Add build dockerfile

- csmtest/include/csm_fvt_xcat_setup_on_non_mn.sh
> Revert "Bills fvt xcat non mn fix"

- csmtest/include/csm_fvt_xcat_setup_on_non_mn.sh
_Modify variables to use XCATMN as IP ADDRESS"_
> had to modify a couple variables to reflect the XCATMN.

- bb/scripts/bbactivate.pl
One node with lvs on RHEL8.2 returned:
/dev/sda: open failed: No medium found
messages to stderr.  This patch ignores stderr.
> Ignore stderr from lvs command

- bb/ansible/bbInstall.yml
- bb/ansible/bbUninstall.yml
- bb/ansible/hosts
- bb/fvt-ansible/csmInstall.yml
- bb/fvt-ansible/csmUninstall.yml
- bb/fvt-ansible/update.yml
> Use dnf and potentially pull from a remote repo

- bb/CMakeLists.txt
Change 2.9.6 to 2.9.5.. matching standard RHEL8 levels.
> Fix minimum ansible RPM version

- bb/include/bbapiAdmin.h
- bb/src/bbcmd.pod
- docs/source/burst-buffer/cli/bbcmd.rst
Added man and docs for getfileinfo bbcmd late add.
> Add man and docs for gitfileinfo

- csm_big_data/python/cast_helper.py
- csm_big_data/python/findJobKeys.py
- csm_big_data/python/findJobMetrics.py
- csm_big_data/python/findJobTimeRange.py
- csm_big_data/python/findJobsInRange.py
- csm_big_data/python/findJobsRunning.py
- csm_big_data/python/findUserJobs.py
- csm_big_data/python/findWeightedErrors.py
- csmtest/buckets/BDS/python_scripts.sh
These fixes are related to issues #990 and #991 that Thanh and myself have been working on.
Examples and updates have been done in the issues tracker.
> CSM BDS fixes related to open IST issues.
