- README.md
> Fix spelling of license in README

- csmd/src/daemon/src/csm_daemon_config.cc
- csmnet/include/csm_network_config.h
- csmnet/src/CPP/csm_version_msg.cc
- csmnet/src/CPP/csm_version_msg.h
- csmnet/src/CPP/reliable_msg.cc
- csmnet/tests/CMakeLists.txt
- csmnet/tests/csm_version_msg_test.cc
- csmutil/include/CMakeLists.txt
Updated csmd to new version format and introduced back-level support for N-1 cumulative fix versions.
Also added 2 explicit git commits of the cast 1.0.0 branch that could be out there in the wild and would need to be supported.
Current limitation: the introduction of the jsrun command shifted the daemon-internal command IDs by one. Need to work on support for that.
> updated csmd versioning to use major.cumulative.efix format instead of git commit

- csmd/src/inv/ib_and_switch/src/standalone_ib_and_switch_collection.cc
If inventory collection API fails, then it would cause a segfault. This code checks for success. And only runs the code in case of a success, therefore avoiding a potential read of values that don't exist. eliminating a potential segfault.
> CSM Inventory: fix potential seg fault issue

- csmd/src/daemon/tests/csm_daemon_echo_test.cc
- csmi/src/common/include/csm_cmds_internal_def.h
- csmi/src/common/tests/test_csmi_corner_cases.c
- csmnet/src/CPP/endpoint_unix.cc
Since we're reworking the API enums to be stable in the future and that rips up the enum anyway, I think, it's the right time to clean up the internal API section and remove unused/old stuff.
> review/cleanup of internal API commands

- csmd/src/daemon/src/csmi_request_handler/csm_infrastructure_test.h
- csmd/src/daemon/src/csmi_request_handler/csm_infrastructure_test_agent.cc
- csmd/src/daemon/src/csmi_request_handler/csm_infrastructure_test_master.cc
- csmnet/src/CPP/reliable_msg.cc
In earlier versions, we always shortened the git commit id when we printed the version. Now, we have version numbers where the length might be shorter than the existing forced limit. That causes trailing 0-bytes or maybe even uninitialized chars in the output of e.g. the health check or the daemon log.
This set of patches will limit the length to 10 chars but also never enforces the 10 if the version string is shorter.
@pdlun92 thanks for reporting this. Your check of the health-check output should no longer see the warning about binary file.
> fixing uninitialized chars in version string output

- csmd/src/daemon/src/csmi_request_handler/helpers/DataAggregators.cc
- csmd/src/daemon/src/csmi_request_handler/helpers/DataAggregators.h
`gpu_energy` was not a reference type.
> Fixing data aggregator function parameters.

- csmconf/csm_api.acl
- csmd/src/daemon/src/csmi_request_handler/CSMIAllocationUpdateState.cc
- csmd/src/daemon/src/csmi_request_handler/CSMIAllocationUpdateState.h
Non root users were unable to update the state of their allocations from `running` to `staging-out`, this is due to the private check functions being unimplemented. 
This pull request re-implements the private check and adds `csm_allocation_update_state` to the list of private APIs by default in the acl file.
@pdlun92 We're going to need a new test case to check, I'll make an issue with details.
> csm_allocation_update_state private check bug fix

- csmd/src/daemon/include/connection_handling.h
- csmd/src/daemon/include/csm_daemon_network_manager.h
- csmd/src/daemon/include/csm_daemon_state.h
- csmd/src/daemon/include/csm_event_sink.h
- csmd/src/daemon/include/csm_system_event.h
- csmd/src/daemon/src/connection_handling.cc
- csmd/src/daemon/src/csm_daemon_core.cc
- csmd/src/daemon/src/csm_daemon_network_manager.cc
- csmd/src/daemon/src/csm_daemon_state.cc
- csmd/src/daemon/src/csm_event_sinks/csm_sink_system.h
- csmd/src/daemon/src/csmi_request_handler/csm_ctrl_cmd_handler.cc
- csmd/src/daemon/src/csmi_request_handler/ctrl_cmd_option.h
- csmd/src/daemon/tests/csm_ctrl_cmd.cc
- csmnet/include/csm_network_header.h
- csmnet/src/CPP/network_ctrl_path.h
- csmnet/src/CPP/reliable_msg.cc
This adds a new feature/option to csm_ctrl_cmd:
```
csm_ctrl_cmd --agg.reset
```
This requests a compute daemon to reset it's primary/secondary connections in case the primary/secondary had changed because of aggregator fails/restarts etc.
A few details for whoever is interested:
* new internal ctrl msg between compute and agg to tell a primary agg to reset connection status to secondary - was required because both aggregators stay up and therefore this is not possible to be processed like a failover
* added a system event (RESET_AGG) to allow API handlers to trigger system events (extension of former JOB_START/STOP event handling); this makes it easier to process additional system events in the future
* existing ctrl-cmd extended to trigger the RESET_AGG system event; note: as with the …
> enable ctrl-cmd to reset primary/secondary connection status according to config

- csmd/src/daemon/src/csmi_request_handler/helpers/cgroup.cc
- csmd/src/daemon/src/csmi_request_handler/helpers/cgroup.h
Modified the error logging for cgroups. Now in the event of a failure a list of the pids that can't be killed will be logged to the error utility. 
Moved a warning error message down to debug to reduce confusion.
> Cgroup Debug/Error Logging

- csmd/src/daemon/src/csmi_request_handler/CSMICGROUPLogin.cc
- csmd/src/pamd/src/csm_pam.cc
- csmi/include/csm_types/struct_defs/wm/csm_cgroup_login_input.def
- csmi/include/csmi_type_wm.h
- csmi/src/wm/src/csmi_wm_internal.c
- csmi/src/wm/src/csmi_wm_python.cc
Add 'account' function to pam module where we do not migrate pids, but
do return success/fail.
Modify 'session' function to migrate pids, but always return pam_success
Removed printing of 'permission denied' as it is not appropriate to
print in the middle of the pam stack.
wrap struct changes for migrate_pid flag in CSM_DEVELOPMENT version macros
commit struct changes generated by the regenerate_headers.sh script
Fixes issue #15 .
This is not yet ready for merge.  Current issues are:
1) This requires pull request #24 in order to build, but with that merged in build has been confirmed.
2) The function is untested as I don't have an environment running 4/27 software to test in yet.  Hopefully later this week.
3) API version is still using CSM_DEVELOPMENT for addition to struct.  I'm not …
> Add a flag for csm_cgroup_login to migrate pids on invocation or not.

- csmd/src/daemon/src/csm_daemon_config.cc
The jitter mitigation experiments suggest to set a default of 10 for the number of loops that the netmgr would stay alive looking for more potential work before going to sleep.
This pull request changes the default for compute nodes to 10 so that the default reflects the recommended value.
In order to test, one would have to perform the jitter tests because these numbers are not logged anywhere yet. Let me know if it's desired to add logging for these numbers/settings.
> csm: change default netmgr polling loops to 10 on compute daemons

- csmd/src/daemon/src/csmi_request_handler/csmi_mcast/CSMIMcastResponder.h
- csmd/src/daemon/src/csmi_request_handler/helpers/cgroup.cc
Implemented a new feature which migrates tasks to the non cpuset system cgroup when the allocation is created. The following cgroups should all have the same number of pids in the `tasks` file after the allocation is created:
* `/sys/fs/cgroup/cpuset/csm_system`
* `/sys/fs/cgroup/memory/csm_system`
* `/sys/fs/cgroup/devices/csm_system`
* `/sys/fs/cgroup/cpuacct/csm_system`
Cgroup tests should be modified to check this in the near future.
> Cgroup improvement, added additional task migration

- csmd/src/daemon/src/csm_daemon_network_manager.cc
- csmi/src/common/src/csmi_common_utils.c
- csmnet/src/C/csm_network_internal_api_c.h
- csmnet/src/C/csm_network_local.c
- csmnet/src/C/csm_network_msg_c.h
- csmnet/src/CPP/endpoint_buffer.h
We noticed that the large-msg protocol for messages from clients to daemon was not functioning as expected. It caused the daemon to receive several invalid messages and the client to get disconnected.
This PR fixes the protocol.
@fpizzano This might be a candidate for a hotfix since it might cause trouble for anything that tries to send CSM API requests larger than 128k.
Will open an issue to add a regression test.
> csm: fix client-to-daemon large message protocol

- csmd/src/daemon/src/csmi_request_handler/CSMIAllocationCreate.cc
- csmdb/sql/csm_create_triggers.sql
Added a fix for Issue #112. Fixes the `to-running` state for diagnostics in allocation create. We need a test case for allocation create with diagnostics.
> Diagnostic fix

- csmd/src/daemon/include/bds_info.h
Looks like we we comparing the int64 constant instead of the int32 constant.
Issue #131
> Fixing the clang build INTMAX_MAX => INT_MAX

- csmconf/csm_aggregator.cfg
- csmconf/csm_api.cfg
- csmconf/csm_compute.cfg
- csmconf/csm_master.cfg
- csmconf/csm_utility.cfg
- csmd/include/csm_daemon_config.h
- csmd/src/daemon/include/csm_api_acl.h
- csmd/src/daemon/include/csm_api_config.h
- csmd/src/daemon/src/csm_bds_manager.cc
- csmd/src/daemon/src/csm_daemon_config.cc
This pull request contains a small set of adjustments to handle configured host names and introduce 'NONE' as an option to ignore a host name setting (currently for secondary aggregator or BDS).
For example, a 'clean' single-aggregator config would look like this:
```
"aggregatorB" :  {
"host": "NONE",
...
```
It also enables to use comments in csm_api.cfg: any command that contains a # will be ignored. See example:
```
{
"# comment" : "more comment",
"also com#ment" : "possible but not recommended",
"csm_allocation_create" : 500,
"csm_allocation_delete" : 60,
...
```
We might want test cases that cover the 3 cases:
* valid entry to enable the config
* invalid entry that causes a warning
* NONE option to explicitly disable
> hostname and command configuration improvements

- csmd/src/daemon/src/csmi_request_handler/csmi_agg_mtc_handler.cc
- csmd/src/inv/src/inv_aggregator_handler.cc
* adds the requestID and csm command type to the MTC handler msgs to improve tracking of requests traveling through the csm infrastructure.
* moves a log line of the inventory handler from info to debug level because this unlikely has any informational value.
* adds node name to the inventory msg logging
> extensions and improvements to logging of multicast and inventory

- csmdb/sql/csm_create_triggers.sql
- there was a typo in the db function "fn_csm_ib_cable_inventory_collection"
- this caused both port_s1 and port_s2 to appear as the same value in the database.
- this pull request removes that typo.
original issue: https://github.com/NickyDaB/CAST/issues/12
> fix duplicate port defect

- csmtest/buckets/basic/hcdiag.sh
- csmtest/include/hcdiag/test.properties
This is a first pass of "basic" (hardware/software-package independent) hcdiag tests to be included in CSM regression.  
List is as follows
```
ppping
chk-csm-health
chk-free-memory
chk-led
chk-boot-time
chk-noping
rpower
chk-load-average
chk-load-cpu
chk-load-mem
chk-power
chk-smt
chk-temp
chk-zombies
test-simple
chk-process
chk-nfs-mount
```
If that looks like an acceptable list for a first pass we can get this pull request merged in upon approval.  I have included a list of additional tests to add in an email to the reviewers.
> Overhaul of CSM FVT for hcdiag: First pass for basic bucket 

- csmtest/buckets/basic/hcdiag.sh
- csmtest/include/hcdiag/clustconf.yaml
- csmtest/tools/complete_fvt.sh
Added a static clustconf.yaml to be distributed for hcdiag regression. Also added the test cases that are dependent on that file to basic hcdiag bucket.
Added in this commit:
```
chk-cpu
chk-cpu-count
chk-sys-firmware
chk-memory
chk-aslr            
chk-os
chk-temp
```
Once approved I will merge to master
> CSM FVT regression test cases for hcdiag that require clustconf.yaml

- csmi/src/wm/cmd/allocation_query_active_all.c
Fix issue of compute nodes not printing in **csm_allocation_query_active_all**
- there was an issue where above 200+ ish compute nodes would not print.
- issue was somewhere in the csm internal formatting printer.
- until further investigation can be done with the printer. we stopped using the tool.
- expected functonailty has been preserved here. the users will notice no change in use of this api cmd line wrapper, with the exception that all compute nodes will print.
- removes calls to internal printer
- manually prints fields in the cmd line wrapper
@pdlun92 - please make sure this pass all tests that **csm_allocation_query_active_all** previously passed. please add a test case for non matching field names as demonstrated below in screenshots. 
```
[root@c650f03p41 bin]# …
```
> Hotfix - csm_allocation_query_active_all

- csmtest/buckets/basic/bb.sh
In response to git commit: https://github.com/IBM/CAST/commit/98df9f15e14386aeb69d5331b4a84a708d976d35
Regression was using the old built `csm_bb_lv_create` API
this updates the basic bb bucket to use the new API
> CSM FVT basic bb bucket updated for csm_bb_lv_create

- csmd/src/daemon/include/csm_tweaks.h
- csmd/src/daemon/src/csm_daemon_config.cc
- csmd/src/inv/include/inv_dcgm_access.h
- csmd/src/inv/src/inv_dcgm_access.cc
Adds collection of gpu_usage in microseconds on a per node basis. Collection of this data using the DCGM job stats APIs is triggered via csm_allocation_create and csm_allocation_delete.
> Add collection of gpu_usage in microseconds to CSM Allocation handling.

- csmd/src/daemon/src/csmi_request_handler/csm_ctrl_cmd_handler.cc
- csmd/src/daemon/src/csmi_request_handler/ctrl_cmd_option.h
- csmd/src/daemon/tests/csm_ctrl_cmd.cc
Enable log-level change to csmenv component
extended the existing lists of vars and functions to cover csmenv
Future improvements should address this by attempting to generate code based on the log subcomponent definitions.
Go to a compute or aggregator, call the ctrl-cmd to change the csmenv log level
```
csm_ctrl_cmd --log.csmenv debug
```
Then check the csmd logfile and confirm that csmenv::debug entries appear after e.g. an environmental bucket has been triggered (depends on bucket interval in configuration of compute daemon)
> add missing csmenv option to csm_ctrl command

- csmi/src/CMakeLists.txt
Python generation was previously disabled in gcc due to a misunderstanding of the pragma message. This change will now enable the compilation of the CSM python libraries (first pass).
> Enabling python for gcc.

- csmnet/src/CPP/endpoint_ptp.h
- csmnet/src/CPP/endpoint_ptp_sec.cc
- csmnet/src/CPP/endpoint_ptp_sec.h
- csmnet/src/CPP/multi_endpoint.cc
Reviewed the handling of non-blocking connect() for SSL and non-SSL connections between daemons. Potentially has an impact on issue #128 because there were some incorrect socket settings that got fixed.
Needs thorough testing especially with error cases where either the network or the peer daemon is not functioning properly. 
- regular function needs to be preserved
- in case a remote daemon is not responsive (stopped via signal, net cable pulled, firewall up), connection timeouts should be short to reduce the time the network thread waits for the timeout.
- especially important for compute daemons with 2 aggregators where one aggregator is unresponsive
- SSL connection becomes non-blocking with this PR which makes it useful to include SSL error cases too.
> non-blocking connection review

- bb/scripts/bbactivate.pl
- bb/scripts/bbtools.pm
- bb/scripts/epsub.bb
- bb/scripts/nvmet.json
- bb/src/nodecontroller_csm.cc
- flightlog/src/buildFlightRegistry.pl
New option in bbactivate to setup LSF.
Fixes apply to burstbuffer and burstbuffer-lsf RPMs on launch/login nodes, and a switch of the NVMe port to match IANA designation.  
Build issue with flightlogs potentially have a leading zero in the checksum calculation.
> LSF and NVMe fixes

- csmd/src/daemon/src/csmi_request_handler/CSMIRasEventCreate.cc
This pull request contains minor modification to the CSM RAS trace messages to aid in determining how individual RAS events are processed, even when the csmras logging level is set to info. The goal is to provide two trace messages at the info level for every CSM RAS event received. The first message indicates that a new message has been received; the second message indicates what the final result of processing is.
Example traces for different results:
```
2018-09-10 10:27:01.446219     csmras::info     | NEW RAS EVENT        ctx:15 ts:2018-09-10 10:27:01.445917 loc:c650f99p26 msg:csm.status.down
2018-09-10 10:27:01.480834     csmras::info     | RAS EVENT COMPLETE   ctx:15 ts:2018-09-10 10:27:01.445917 loc:c650f99p26 msg:csm.status.down
2018-09-10 10:28:36.498916     csmras::info     | …
```
> Update ras trace messages for consistency and easier debugging

- csmd/src/daemon/src/csmi_request_handler/InvGetNodeInventory.cc
- csmd/src/inv/include/inv_processor_inventory.h
- csmd/src/inv/src/CMakeLists.txt
- csmd/src/inv/src/inv_full_inventory.cc
- csmd/src/inv/src/inv_get_node_inventory_serialization.cc
- csmd/src/inv/src/inv_processor_inventory.cc
- csmd/src/inv/tests/CMakeLists.txt
- csmd/src/inv/tests/test_inv_processor_inventory.cc
- csmi/include/csm_api_consts.h
- csmi/src/inv/include/inv_types.h
This pull request contains support for CSM processor socket inventory collection. The processor socket inventory is collected every time csmd starts, like all node inventory items.
Example trace data and API output:
```
[COMPUTE]2018-09-11 14:21:15.949360       csmd::info     | processor@1000: serial_number = YA1934498223
[COMPUTE]2018-09-11 14:21:15.949393       csmd::info     | processor@1000: physical_location = UOPWR.787C48A-Node0-Proc0
[COMPUTE]2018-09-11 14:21:15.949421       csmd::info     | processor@1000: discovered_cores = 22
[COMPUTE]2018-09-11 14:21:15.950236       csmd::info     | processor@1001: serial_number = YA1934498225
[COMPUTE]2018-09-11 14:21:15.950265       csmd::info     | processor@1001: physical_location = UOPWR.787C48A-Node0-Proc1
[COMPUTE]2018-09-11 …
```
> Added support for CSM processor socket inventory collection

- csmconf/csm_api.cfg
The burst buffer commands can exceed the 30 second CSM default timeout, particularly failover.  Increasing timeout of the csm_bb_cmd() to 2 minutes.
> Change timeout for csm_bb_cmd

- csm_big_data/elasticsearch/mappings/templates/cast-counters-gpfs.json
- csm_big_data/elasticsearch/mappings/templates/cast-counters-gpu.json
- csm_big_data/elasticsearch/mappings/templates/cast-counters-ufm.json
- csm_big_data/elasticsearch/mappings/templates/cast-csm-dimm-env.json
- csm_big_data/elasticsearch/mappings/templates/cast-csm-gpu-env.json
- csm_big_data/elasticsearch/mappings/templates/cast-csm-node-env.json
- csm_big_data/elasticsearch/mappings/templates/cast-csm-processor-env.json
- csm_big_data/elasticsearch/mappings/templates/cast-db-csm.json
- csm_big_data/elasticsearch/mappings/templates/cast-log-console.json
- csm_big_data/elasticsearch/mappings/templates/cast.json
The following pull request makes changes to the timestamp parsers in the elasticsearch index templates. This *should* repair all currently shipped timestamps.
> Fix for environmental, database and step timestamps.

- csmd/src/daemon/src/csmi_request_handler/csmi_forward_handler.cc
Extending the log msg of the FWD handler to include the forwarded error msg
To improve debugging (see #260)
Adjusted the output to the info-level format of csmapi ( line begins with: cmd[id]; ) to help tracing command execution in case of failures.
Start the CSM infrastructure and call an API (anything other than the infrastructure health check) to cause an error (e.g. create allocation on non-existing node)
> csm: issue #260; extended log msg to include forwarded error msg

- bscfs/src/bscfsOperations.cc
Return failure code when the specified mapfile is designated to be on the /bscfs mount point.
> Check that mapfile does not reside in the FUSE mount point

- csmi/src/bb/bb_cmds/CMakeLists.txt
A year ago we had a program `helloworld` that printed "hello world" to the console. we used this program to test the white list feature of the CSM API `csm_bb_cmd`. We no longer want to ship this program in the RPM. @fpizzano  requested this change. No issue was made. 
The CMake file has been edited. the lines where the program was bundled into the RPM have been commented out. 
- *Note*: This makes some test cases located in `csmi\src\bb\tests` no longer able to run correctly because the above program no longer exists. 
- I discuss with @pdlun92 . He said we do not use these test cases, so it is ok. 
1. run an old build
2. see the program there
3. run the new build
2. see that the program is no longer there
> remove bb_cmd test program from RPM

- csmconf/csm_master.cfg
- csmd/src/daemon/include/csm_recurring_tasks.h
- csmd/src/daemon/src/csm_daemon_config.cc
Introduce switches to enable or disable recurring tasks separately or entirely in config
The defaults currently set: false for everything because the corresponding handler only is a placeholder for later development.
```
"recurring_tasks":
{
"enabled" : false,
"soft_fail_recovery" :
{
"enabled" : false,
"interval" : "00:01:00",
"retry" : 3
}
}
```
* With everything set to false, the log should print info-level msg that shows the feature disabled.
* same should happen if you enable just the soft-fail-recovery section
* If recurring.tasks.enabled = true, the log should print info-level msg that indicates the feature disabled because there are no active tasks
* if both is set true, you should see info-level msg showing the settings for soft-fail-recovery (and the values should match the …
> csm: add switches to enable/disable recurring tasks in config

- csmdb/sql/CMakeLists.txt
- csmdb/sql/csm_create_tables.sql
- csmdb/sql/csm_create_triggers.sql
- csmdb/sql/csm_db_schema_version_data.csv
- csmdb/sql/csm_db_schema_version_upgrade_16_1.sh
- csmdb/sql/csm_delete_data.sql
- csmdb/sql/csm_drop_functions.sql
- csmdb/sql/csm_drop_tables.sql
16.1 migration script along with
Update 'fn_csm_ssd_dead_records' and 'fn_csm_ssd_history_dump'
now clean up any lvs and vgs on an ssd before we delete the ssd from table.
> csmdb_migration_script_16_1_with_ssd_inventory_support

- csmd/src/inv/ib_and_switch/include/inv_switch_connector_access.h
- csmd/src/inv/ib_and_switch/src/inv_ib_connector_access.cc
- csmd/src/inv/ib_and_switch/src/inv_switch_connector_access.cc
- csmd/src/inv/ib_and_switch/src/standalone_ib_and_switch_collection.cc
we dont want to create output and log files in the same directory that we run the inv collection for ufm
- store logs and output to dir specified in master config
- also makes output file names more obvious
1. run the ib switch inv collection
2. look in `/var/log/ibm/csm/inv`
3. Do you see the new files: 
```
[root@c650f03p31-mgt inv]# ls -l
total 100
-rw-r--r-- 1 root root  4553 Mar  6 23:35 bad_ib_cable_records.txt
-rw-r--r-- 1 root root 52440 Mar  6 23:35 ufm_ib_cable_output_file.txt
-rw-r--r-- 1 root root 40361 Mar  6 23:35 ufm_switch_output_file.txt
```
4. look in the ./ dir where you ran the collection program. you should no longer see an "output.txt" file
@pdlun92 you may need to update older test cases for UFM inv collection.
>  change log and output file location for UFM inv collection

- csmd/src/daemon/include/bucket_item_type_definitions.h
- csmd/src/daemon/include/csm_bds_keys.h
- csmd/src/daemon/include/csm_environmental_data.h
- csmd/src/daemon/src/csm_environmental_data.cc
- csmd/src/daemon/src/csmi_request_handler/csm_environmental_handler.cc
Adding a debug or test source for environmental data collection and BDS testing.
When running on a system that's not P9 and/or has no DCGM active, there will be no environmental data collection visible to the user or the aggregator or to BDS. This PR adds a DEBUG source that sends some fixed data (+time stamp and host name) an an env-data dummy.
The sole purpose is for testing if the env data from the compute node arrives in BDS at the configured interval for testbeds that have no hardware or firmware support for our existing data collection.
When configuring:
```
"data_collection" :
{
"buckets":
[
{
"execution_interval":"00:00:10",
"item_list" : ["debug"]
}
]
}
```
This is an example test string that would be sent to BDS every 10s:
``` …
```
> add debug/test env-data source

- csmd/src/daemon/src/csm_environmental_data.cc
- csmd/src/daemon/src/csmi_request_handler/helpers/OCCSensorData.cc
- csmd/src/daemon/src/csmi_request_handler/helpers/OCCSensorData.h
OCC sensors provide a current value and min and max value for each sensor. The intended use of the min and max value is to capture the most extreme variations in sensor values that occur during a particular sample period. This pull request implements support in CSM for resetting the min and max values that CSM monitors so that they represent the min and max values that occurred since the last time CSM read the sensor values.
Some example data showing how the min and max sensors behave now that they are reset during each data collection period. In this test, the GPUs start out idle, then ramp up to run a heavy workload for 30 seconds, then return to idle. The data below is 8 data points for the same GPU, collected every 10 seconds. The data below shows periods where the temperature min and …
> Reset OCC CSM sensor min and max values whenever environmental data is collected

- csmdb/sql/csm_history_table_archive_template.sh
Clean up stray whitespace.
Remove the unused variables.
Drop the initial "if [ $? -ne 127 ]; then" conditional.  This appears
to do little of actual use.  It would be checking the return code from
this line:
time="$(time ( ls ) 2>&1 1>/dev/null )"
This seems to do nothing more than check if the "ls" command exists.
That seems like a silly check.  Even if checking for the runability
of "ls" made sense, the error and exit should happen immediately after
the check.  We shouldn't wrap the entire real work in this conditional.
Next, the actual psql command.  The output from the command is saved
to a variable named archive_count_$table_name.  This variable is
unused, so we remove that.  Next the command is wrapped in _two_
different subshell mechanisms, $() and ``.  That seems unnecessarily …
> General script cleanup

- csmd/src/daemon/src/csm_environmental_data.cc
This pull request removes GPU sensor output with invalid data from the set of collected data in the environmental bucket.
Example data collected prior to this code change on a 4 GPU system:
```
{"type":"csm-gpu-env","source":"c650f99p18","timestamp":"2018-10-02 16:09:41.001035","data":{"gpu_id":"0","gpu_temp":"23","gpu_temp_min":"23","gpu_temp_max":"24","gpu_mem_temp":"22","gpu_mem_temp_min":"21","gpu_mem_temp_max":"22"}}
{"type":"csm-gpu-env","source":"c650f99p18","timestamp":"2018-10-02 16:09:41.001035","data":{"gpu_id":"1","gpu_temp":"22","gpu_temp_min":"22","gpu_temp_max":"24","gpu_mem_temp":"21","gpu_mem_temp_min":"21","gpu_mem_temp_max":"22"}}
{"type":"csm-gpu-env","source":"c650f99p18","timestamp":"2018-10-02 16:09:41.001035","data":{"gpu_id":"2","gpu_temp":"0","gpu_temp_min":"65535 …
```
> CSM ENV: remove GPU temperature sensors with invalid values from collected data

- csmd/src/daemon/src/csm_bds_manager.cc
- csmnet/src/CPP/endpoint_ptp.h
Non-blocking connection to BDS to solve issue #248 
same mechanism as for daemon-to-daemon connections via non-blocking socket and check for activity via select with short timeout to avoid having to wait the default network timeout in worst case.
- So far, I haven't bothered to change the whole communication with BDS into non-blocking. So there's still some potential for send() operations to get stuck until timeout.
I have not been able to reliably reproduce the stuck connection.
Since we've never seen this in the wild, testing should focus on 'existing functionality preserved' for now. I'll update issue/PR/test team if I stumble over the problem again
the diff of endpoint_ptp.h shows an unrelated function being moved when actually CheckConnectActivity() has been moved to public and made …
> non-blocking BDS connect

- csmd/src/inv/ib_and_switch/src/standalone_ib_and_switch_collection.cc
we found a temp file that shouldnt exist. 
- uncomments a line that removes temp file
- but i'm not sure if we even need to use this temp file to store the data in this way. 
- will look for a better way to avoid making this temp file all together. 
1. if you run the `standalone_ib_collection` program a file named `temp_file.txt` would appear in the directory where you run it
2. now it doesnt
preview after: 
```
[nbuonar@c650f03p41 sbin]$ pwd
/u/nbuonar/repos/CAST/work/csm/sbin
[nbuonar@c650f03p41 sbin]$ 
[nbuonar@c650f03p41 sbin]$ 
[nbuonar@c650f03p41 sbin]$ ls -l
total 296576
-rwxr-xr-x 1 nbuonar users   6060056 Oct  3 14:28 csm_ctrl_cmd
-rwxr-xr-x 1 nbuonar users 134253440 Oct  3 14:28 csmd
-rwxr-xr-x 1 nbuonar users   9901368 Oct  3 14:27 csmrestd
-rwxr-xr-x 1 nbuonar users      2661 …
```
> remove the temp file

- csmconf/csm_aggregator.cfg
- csmd/src/daemon/include/bds_info.h
- csmd/src/daemon/include/csm_bds_manager.h
- csmd/src/daemon/src/csm_bds_manager.cc
- csmd/src/daemon/src/csm_daemon_config.cc
This PR introduces a limited reconnect frequency for BDS access.
The pull request will prevent the BDS mgr from trying to connect for each and every env data item that arrives at an aggregator. Instead, it will only try to connect after a configurable interval.
The interval will increase from 1s to the configured max to allow more frequent retries after initial failure and slow down the connection attempts as it keeps failing.
The BDS mgr remembers the time of the last failed connection attempt as well as the current interval for retries. Each time a new request arrives, it checks whether a new connection attempt is due or not.
1. Setup an env source with a short interval (to see the effect quicker)
2. Start test env (all daemons) without running BDS, so the connections fail
3. Each time …
> limiting BDS reconnect frequency

- csmd/src/daemon/src/csm_daemon.cc
- csmd/src/daemon/src/csm_daemon_config.cc
This PR removes any additional output from execution of ```csmd -h```
It performs a rough exit(0) instead of a detailed tear-down, however, it should be fine because at that point there are not many structures created (if any at all).
> csm: candidate solution for #311 preventing additional output or errors

- utilities/src/string_tools.c
addresses issues raised in #318 
- working on https://github.com/IBM/CAST/issues/318
- change the starting pointer location for the search
1. reproduce the screenshot in #318 
2. reproduce screenshot below after new code. 
```
[root@c650f03p31-vm02 bin]# ./csm_node_attributes_update -n c650f03p31-vm[06-09] -s "ADMIN_RESERVED"
---
...
```
> change the starting pointer location for the search

- bb/scripts/bbactivate.pl
- bb/scripts/bbactivate.pod
Shutdown of Spectrum Scale was inhibited by bbServer running on the I/O nodes.  This fix adds an option to shutdown burst buffer services that can be called via mmaddcallback.  
e.g.,:
mmaddcallback BBShutdown --command /opt/ibm/bb/scripts/bbactivate --parms '--shutdown' --event preShutdown
> Add shutdown option to bbactivate for mmaddcallback

- hcdiag/src/framework/hcdiag_run.py
Fixes the following exception:
```
Traceback (most recent call last):
File "/opt/ibm/csm/hcdiag/bin/hcdiag_run.py", line 186, in <module>
console_level=VERBOSE_LEVEL[mconfig['console_verbose'].lower()]
KeyError: 'warn'
```
I'm an IBMer, no need for CLA.
> hcdiag: Fix missing 'warn' key in VERBOSE_LEVEL

- bb/src/connections.cc
If bbproxy is killed while bbcmd has a message outstanding to bbproxy, bbcmd will hang.
The code change registers the bbcmd waiting for reply and cancels it if the socket connection to bbproxy ends.
> Issue998 bbcmd waitreplyhang

- bb/scripts/bbactivate.pl
bb.cfg should be marked 0644, but its possible the bbactivate caller's umask may not be 0022.
> Explicitly mark configuration file as readable by group/other

- bb/scripts/bbactivate.pl
The nvmetcli tool does not currently display helpful error text when it fails.  Executing bbactivate on a node without an SSD is not easily determined.  This patch checks the NVMe existence before calling nvmetcli to setup the NVMe over Fabrics target.
> Improve error handling when NVMe device does not exist

- bb/scripts/bbtools.pm
The transfer query code was moved into the bbtools package, but referenced variables in the main namespace.
> Fix transfer status query

- csmconf/csm_aggregator.cfg
- csmd/src/daemon/include/bds_info.h
- csmd/src/daemon/include/csm_bds_event.h
- csmd/src/daemon/include/csm_bds_manager.h
- csmd/src/daemon/src/csm_bds_manager.cc
- csmd/src/daemon/src/csm_daemon_config.cc
- csmd/src/daemon/src/csm_event_sinks/csm_sink_bds.h
This pull request will add a caching feature to the aggregator.
If the aggregator has lost the connection to the BDS, it will cache any BDS messages (e.g. environmental data from compute nodes) for a configurable amount of time.
This will help to prevent BDS data to get dropped due to temporary failures or restarts of the BDS service.
The expiration time of cached messages can be configured in the config file via a new option:
```
"bds" :
{
"host" : "__LOGSTASH__",
"port" : 10522,
"reconnect_interval_max" : 5,
"data_cache_expiration" : 50
}
```
* If the ```data_cache_expiration``` parameter is omitted, there will be a default expiration time that is 5x of the configured (or default) reconnect interval.
* If expiration is set to 0, then caching is disabled and data gets dropped while the …
> BDS msg caching at aggregator

- docs/source/csmd/csm_daemon.rst
- docs/source/csmd/index.rst
- docs/source/index.rst
Added an initial documentation file that explains the settings of the csm config file as well as the ACL and API-cfg. With exclusive focus on the csm section. So there's more to come.
There are a few items that I don't know much about and left them as tbd waiting for the owners to jump in and explain. However, the current status should cover a lot of things already.
I think, it'll need some small input from @NickyDaB to update the csm.inventory section and @besawn to help with the csm.ufm section.
I'm sure it will require some review of the language too.
It's also not yet covering the restd section.
> csm: adding initial documentation for daemon and api configuration

- bb/tests/resiliency/tools.robot
LV size was too small for testcase.  Increasing to 64GB.
> Increase testcase LV size to accommodate multiple transfers

- csmd/src/ras/ufm/convert_ufm_policy_to_csm_ras_types.sh
- csmd/src/ras/ufm/ufm_csm_ras_type_data.csv
This pull request contains a first pass at a script to automatically generate CSM RAS msg types from UFM event policy files and the resulting csv file suitable for importing into CSM for testing.
I intend to add additional commits to this pull request and eventually merge it as part of the CSM 1.4 release in a few weeks.
For now, it is available for @NickyDaB to review the proposed msg types and start testing with.
The message types can be imported into CSM for testing by doing the following:
```
systemctl stop csmd-master
cp ufm_csm_ras_type_data.csv /opt/ibm/csm/db/
/opt/ibm/csm/db/csm_db_ras_type_script.sh -l csmdb ufm_csm_ras_type_data.csv
rm /opt/ibm/csm/db/ufm_csm_ras_type_data.csv
systemctl start csmd-master
```
> CSM RAS: Add CSM RAS msg types for UFM Events

- csmi/src/ras/src/csmi_ras_event_create.c
Lars discovered a problem with csmi_ras_event_create while testing csmrestd on his laptop:
```
[csmapi][error] Failed to pack arguments, make sure version is set!
(null) FAILED: errcode: 28 errmsg: Message packing error
```
Valgrind also detected the following errors that went away after the fix contained in this pull request was applied:
```
==122293== Conditional jump or move depends on uninitialised value(s)
==122293==    at 0x40E828C: serialize_csm_ras_event_create_input_t (csmi_ras_serialization.c:330)
==122293==    by 0x40E2A07: csm_ras_event_create (csmi_ras_event_create.c:59)
==122293==    by 0x10001E0F: main (csm_ras_event_create.c:184)
==122293== 
==122293== Conditional jump or move depends on uninitialised value(s)
==122293==    at 0x40E7904: len_csm_ras_event_create_input_t …
```
> CSM API: Added call to csm_init_struct in csmi_ras_event_create to initialize struct version_id

- csmtest/buckets/basic/bb.sh
- csmtest/buckets/basic/fvt_allocation_create_and_delete.py
- csmtest/buckets/basic/fvt_node_attributes_query_and_update.py
- csmtest/buckets/basic/python_libraries.sh
- csmtest/buckets/error_injection/allocation.sh
- csmtest/config.template
- csmtest/include/hcdiag/clustconf.yaml
- csmtest/setup/csm_install.sh
- csmtest/tools/complete_fvt.sh
- csmtest/tools/update_computes_in_service.sh
Several improvements to CSM regression including:
- Updated error codes according to Pull Request #382 
- New bucket and sub-components for testing CSM python libraries
- Additional test cases for cascading allocation/lv delete functionality in basic csm_bb bucket
- Allow for install script to connect to BDS
- New tool(s) to update nodes to IN_SERVICE for manual test cases
- Additional fields added to included clustconf.yaml for hcdiag regression in FVT environment
Will leave this as an open Pull Request for a while in case anybody wants to take a look / try to catch a mistake.  But I do think we want to get this merged as soon as possible.  I've been running regression using this branch for the past few days and has functioned properly
> CSM FVT Improvements

- csmconf/csmrestd.cfg
- csmrestd/src/CMakeLists.txt
- csmrestd/src/RestApiServer.cc
- csmrestd/src/csmrestd.cc
This enables the restd logging as intended by the restd config file.
The logging was running unconfigured in existing code because the setup code was commented out and some parts were using very outdated ways to find and configure the logging. This has been fixed and therefore logging is enabled now.
The PR also adds several new log lines to help debugging problems.
> Enabling and extending logging capabilities of csm restd

- csmdb/sql/csm_db_history_archive.py
Remove stray open parenthesis.
Fixes #392
> Fix csm_db_history_archive.py parse error

- bb/src/connections.cc
When bbserver returns 0 devices on the Hello response, bbproxy now disconnects from the bbserver.
A query of active connections against bbproxy will show no active servers.
Tested using gdb and setting rc to nonzero after calling sayHello.  Small change (two lines of code).
> Issue 1006: disconnect from bbserver on hello having zero devices

- bb/src/connections.cc
- transport/include/Msg.h
Take advantage of being already under connection lock to add connection info to the logging of the connection name and message ID being sent.
> When connection name is logged on send, add conn info

- csmd/src/daemon/src/csmi_request_handler/CSMIRasEventCreate.cc
This pull request contains the fix for issue #417.
The symptom of this issue is steadily increasing memory usage of the csmd master daemon over time as RAS events are created. The problem was first noticed due to large numbers of "bb.net.SSLconnectAttemptFailed" being created on a large system running CAST v1.3.0 versions of CSM and burstbuffer.
The CSM RAS Event Create handler involves multiple steps for handling each event. In order to maintain state about these events as they are processed, event context is stored for each event. The issue was caused by failing to remove this event context information after event processing is complete.
Remove the event context information after processing is complete for each RAS event.
I have a test case available here: …
> CSM RAS: fixed memory leak by removing completed event contexts from _contextMap

- csmd/src/daemon/include/csm_bds_manager.h
- csmd/src/daemon/include/csm_timer_event.h
- csmd/src/daemon/include/interval_trigger.h
- csmd/src/daemon/include/message_control.h
- csmd/src/daemon/include/throttle.h
- csmd/src/daemon/include/virtual_network_channel.h
- csmd/src/daemon/src/csm_bds_manager.cc
- csmd/src/daemon/src/csm_db_manager.cc
- csmd/src/daemon/src/csmi_request_handler/csm_infrastructure_test.h
- csmd/src/daemon/src/csmi_request_handler/csm_infrastructure_test_master.cc
- csmd/src/daemon/src/message_control.cc
- csmd/src/db/include/DBConnectionPool.h
- csmnet/src/CPP/endpoint_heartbeat.h
- csmnet/src/CPP/endpoint_multi_unix.cc
- csmnet/src/CPP/endpoint_multi_unix.h
- csmnet/src/CPP/endpoint_ptp.cc
- csmnet/src/CPP/endpoint_ptp_sec.cc
- csmnet/src/CPP/message_ack.h
This PR replaces csmd usage of system_clock with steady_clock to reduce the chances for hickups when timezone changes between daylight and standart time or the clock gets adjusted for other reasons.
Especially covering any adjustments where the new time is in the past. This would cause any timers to take longer to trigger causing delays in heartbeats (e.g. for connection error detection) and other timers that got set to observe API timeouts and more.
There are a few instances of system time left in the CSM API section that would have to be reviewed by corresponding code owners (probably @NickyDaB or @mew2057). As far as I can tell, the changes in this PR have no impact on the creation of any user-visible or BDS-inserted time stamps. @besawn might want to check that statement from the RAS …
> csm: using steady clock

- csm_big_data/logstash/patterns/events.yml
Dev goal of: creating CSM RAS events from ufm events.
issue: https://github.com/NickyDaB/CAST/issues/16
1. ufm event logs are sent to the logstash node as a `log-mellanox-event` event
2. the logstash parses through incoming events and looks for the `eventlog` program
3. that triggers the `MELLANOXMSG` pattern
4. that parses the message and extracts the values
5. from those values we use event correlator and construct a CSM RAS event
6. ras event is generated and stored on the csmdb connected to the logstash node.
There is an event triggering in ufm every five minutes. You can look for that in the csmdb. 
Example: 
ufm logs:
```
Nov 27 16:23:09 c650ufm03 eventlog[182483]: CRITICAL - 2018-11-27 16:23:09.423 [665916] [627] CRITICAL [Maintenance] Grid [Grid]: Monitoring History partition …
```
> CSM RAS and UFM Event integration

- csmutil/csm_log_utility/API_Statistics.py
- csmutil/csm_log_utility/Helper_Files/Aggregator_Stat.py
- csmutil/csm_log_utility/Helper_Files/Compute_Stat.py
- csmutil/csm_log_utility/Helper_Files/Master_Stat.py
- csmutil/csm_log_utility/Helper_Files/Utility_Stat.py
- fix time search span issue
- new options to order and filter results
- multi threading causes out of order prints in the terminal window
- not that big of an issue because we also write data to individual report files for each log.
- by doing that you can view each piece of data nice and pretty
- these can be found in the report directory 
- run with `-h` to see all the options
- test all the options, see if get expected results
default:
```
[root@c650f03p41 tools]# python API_Statistics.py -p /u/nbuonar/csm_test_logs/
Search from:  1000-01-01 00:00:00 to 9999-01-01 00:00:00
['/u/nbuonar/csm_test_logs//csm_master.log']
Master: /u/nbuonar/csm_test_logs//csm_master.log
+++++++++++++++++++++++++++++++++++++++++++++++++++++Master Log++++++++++++++++++++++++++++++++++++++++++++++++++++ …
```
> Csm api logging tools

- csmconf/csm_api.cfg
- csmd/src/daemon/src/csmi_request_handler/CSMISoftFailureRecoveryAgentState.cc
- csmd/src/daemon/src/csmi_request_handler/helpers/Agent.h
Added a default timeout time, added utility to print around recovery script calls. 
Fixed a bug in timeouts for both soft failure recovery and bb_cmd. This bug was due to CSM not waiting long enough to process the recovery. Added a fudge time to resolve.
> Soft Failure Recovery Enhancements

- csmdb/sql/csm_db_history_archive.py
csmdb_update: archive_history_db_default_thread_count set to 10
optimize DB connection size for archiving history tables.
> csmdb_update: archive_history_db_default_thread_count set to 10

- csmd/src/daemon/src/csmi_request_handler/CSMIRasEventCreate.cc
- csmd/src/daemon/src/csmi_request_handler/CSMISoftFailureRecovery.cc
- csmd/src/daemon/src/csmi_request_handler/CSMISoftFailureRecovery.h
- csmd/src/daemon/src/csmi_request_handler/csmi_handler_context.cc
- csmd/src/daemon/src/csmi_request_handler/csmi_handler_context.h
- csmd/src/daemon/src/csmi_request_handler/csmi_handler_state.cc
- csmd/src/daemon/src/csmi_request_handler/csmi_mcast/CSMIMcast.h
- csmd/src/daemon/src/csmi_request_handler/csmi_mcast/CSMIMcastAllocation.h
- csmd/src/daemon/src/csmi_request_handler/csmi_mcast/CSMIMcastBB.cc
- csmd/src/daemon/src/csmi_request_handler/csmi_mcast/CSMIMcastBB.h
- csmd/src/daemon/src/csmi_request_handler/csmi_mcast/CSMIMcastJSRUN.cc
- csmd/src/daemon/src/csmi_request_handler/csmi_mcast/CSMIMcastJSRUN.h
- csmd/src/daemon/src/csmi_request_handler/csmi_mcast/CSMIMcastSoftFailureRecovery.cc
- csmd/src/daemon/src/csmi_request_handler/csmi_mcast/CSMIMcastSoftFailureRecovery.h
- csmd/src/daemon/src/csmi_request_handler/csmi_mcast/CSMIMcastSpawner.h
- csmd/src/daemon/src/csmi_request_handler/csmi_mcast/CSMIMcastStep.cc
- csmd/src/daemon/src/csmi_request_handler/csmi_mcast/CSMIMcastStep.h
- csmd/src/daemon/src/csmi_request_handler/csmi_network_message_state.h
- csmi/include/csm_api_ras_keys.h
- csmi/src/wm/cmd/soft_failure_recovery.c
- docs/source/cast-big-data/kibana.rst
- docs/source/csm/soft_failure.rst
Fixes for some of the Soft Failure Bugs uncovered in test:
1. Transitioned to use RAS events to trigger hard failure.
2. Enhanced debug lines in error output (fixed commas, non errors don't present error messages).
3. Enabled Soft Failure to Hard Failure through RAS events.
4. Added mechanism to push events from multicast customization.
Test cases that need to be made:
1. Call soft failure recovery with no nodes in soft failure (`CSMI_NO_RESULTS`).
2. Call soft failure recovery with one node in soft failure (`CSMI_SUCCESS`).
3. Call soft failure recovery with multiple nodes in soft failure (`CSMI_SUCCESS`).
4. Call soft failure recovery with one node in soft failure in an allocation (`CSMI_NO_RESULTS`).
5. Call soft failure recovery with one node in soft failure in an allocation and one …
> Soft Failure Bug Fixes

- utilities/include/logging.h
- utilities/src/logging.cc
Request from labs in today's BDS discussion. Adding `@timestamp` to the transactional and metric logs.
psql timestamps are proper ISO 8601, but elasticsearch has a problem with nanoseconds. Rather than drop data, our recommendation will be the existing index solution or logstash changes, documentation coming soon.
> Transactional logs now have original create data.

- csmd/src/daemon/src/csmi_request_handler/csmi_mcast/CSMIMcastAllocation.h
- csmd/src/daemon/src/csmi_request_handler/csmi_mcast/CSMIMcastBB.h
- csmd/src/daemon/src/csmi_request_handler/csmi_mcast/CSMIMcastJSRUN.h
- csmd/src/daemon/src/csmi_request_handler/csmi_mcast/CSMIMcastSoftFailureRecovery.h
- csmd/src/daemon/src/csmi_request_handler/csmi_mcast/CSMIMcastStep.h
- csmd/src/daemon/src/csmi_request_handler/csmi_network_message_state.h
Fixing bad network error codes to be transformed into `CSMERR_GENERIC` to prevent loss of error data.
> Fixing error code for daemon being down.

- csmd/src/daemon/src/csmi_request_handler/csmi_handler_state.cc
- csmd/src/daemon/src/csmi_request_handler/csmi_mcast/CSMIMcastResponder.h
- csmd/src/daemon/src/csmi_request_handler/csmi_mcast/CSMIMcastSoftFailureRecovery.cc
Fixing a bug uncovered in regression by @pdlun92 where the multicast was not returning a set error code.
> Fixing responder error where error codes weren't set.

- bb/tools/removefiles.cc
RemoveFiles is sometimes called in FVT during cleanup processing without a valid filelist, causing the test suite to incorrectly abort.
> Tolerate bailout on removefiles tool

- csmtest/buckets/basic/db_script.sh
Added a simple call and check for `csm_db_backup_script_v1.sh` to `CAST/csmtest/buckets/basic/db_script.sh`.  Going to fast track this pull request, since it is a minor change, but purpose of pull request is two-fold
1. Add coverage for `csm_db_backup_script_v1.sg` to CSM FVT regression
2. Changes to serve as reference for @williammorrison2 while he implements additions to regression for remaining CSM DB utility scripts
> CSM FVT: Added csm_db_backup_script_v1.sh to basic db script bucket

- csm_big_data/beats/config/filebeat.yml
- docs/source/cast-big-data/data-aggregators.rst
Simple rename for the filebeats file to handle deprecation of prospectors.
Doesn't need regression, doc and BDS changes only.
> Issue #496: prospectors->inputs.

- csmi/src/common/src/csm_api_common.c
- csmnet/src/C/csm_network_local.c
PR solved race condition and deadlock possibility when client lib tears down the link to the CSMD in case of either disconnect msg from daemon or other connection problems.
The approach is to extend the usage of an existing mutex that was supposed to prevent init and term of the lib to interfere. This mutex is now used to make sure termination waits until a recv/send returns and vice versa. It also prevents a recv/send from getting processed while the link data structures get cleaned up.
I believe, a possible deadlock during disconnect existed for a long time, it's just that the probability seemed very low to hit it. The problem was that multiple code paths were possible to enter the disconnect. However, if the main thread performs the disconnect (with the lock aquired) it also terminates …
> prevent client lib race condition: socket tear-down and pending send/recv

- csmtest/buckets/error_injection/infrastructure.sh
- csmtest/tools/enable_ssl.sh
New CSM FVT tool `enable_ssl.sh` will edit and distribute configuration files to FVT cluster to enable daemon-to-daemon SSL connections.  `enable_ssl.sh` is available for standalone use and incorporated in to new infrastructure error injection test cases to exercise the SSL daemon-to-daemon connection functionality.
New test cases are fairly straight forward:
- Bring up master, aggregator, utility, compute daemons in order. Query connections intermittently
- Tear down connections by stopping compute, utility, and aggregator daemons in order.  Query connections intermittently 
We can discuss adding additional test cases/conditions for passing test run, but I think this is good as a first pass
> CSM FVT: Added new enable_ssl.sh tool and SSL test cases to infrastructure bucket

- utilities/include/logging.h
`@timestamp` is now `timestamp` in BDS logging for metrics and transaction logs.
> Issue #530: Transitioning @timestamp to timestamp.

- bb/src/BBLV_Metadata.cc
Change count++ to ++count to save the additional storage from using the post-increment.
For example consider the following:
```
class Integer {
public:
// Sample implementation of pre-incrementing.
Integer & operator++() {
myInt += 1;
return *this;
}
// Sample implementation of post-incrementing.
const Integer operator++(int) {
Integer temporary = *this;
++*this;
return temporary;
}
private:
int myInt;
};
```
The additional copy (temporary) in post-incrementing step is unnecessary.
> Prefer Pre-Incrementing rather than Post-Incrementing

- bb/src/bbcmd.cc
Handle blank lines in file list file
Tested with \n termination with blanks and/or tabs and neither.
Regression Tested against robot in sandbox.
> bbcmd copy will ignore blank lines in file list of transfers

- csm_big_data/transition-scripts/metric-transaction_140-150.py
- docs/source/cast-big-data/python-guide.rst
- utilities/include/logging.h
Fixes an issue where the CSM log collides with the filebeats source field described in Issue #535. The fix moves the `source` field to the `data.source` field.
Wrote a python script to transition existing logs from the old schema to the new one, this script does require the old data to be removed or moved in the BDS.
@pdlun92 This needs a basic regression as the logging mechanism has a slight change.
> Fix for Issue #535. Moved source location in filebeats output.

- csm_big_data/logstash/patterns/events.yml
- csm_big_data/logstash/patterns/mellanox_grok.conf
Currently all CSM RAS events generated from UFM events are created with a `location_name` of the originating UFM box. Yet some of the events, even though technically generated from the UFM box, are logically generated from other hardware devices. Example: A fan is pulled from switch: `abc123`.  In this example it would be nice if the CSM RAS event reported the  `location_name` to be the switch's hostname of `abc123` and not `ufmbox-01`. 
This pull request extracts the true location name (for appropriate UFM events) and updates that field for CSM RAS events. 
We detected more patterns in UFM events. There is a core UFM message that is consistent across all UFM event messages. 
It consists of a timestamp, log counter, event id, severity level, event type, and category. 
``` …
```
> CSM / UFM Integration - Feature Improvement

- csmdb/sql/csm_create_triggers.sql
Fixing a bug in the SQL statement for the update state Stored Procedure.
The shared column was leftover from a previous iteration of the procedure.
> Fixing bug with SMT mode in allocation update state.

- csm_big_data/elasticsearch/mappings/templates/cast-allocation.json
- csm_big_data/elasticsearch/mappings/templates/cast-counters-gpfs.json
- csm_big_data/elasticsearch/mappings/templates/cast-counters-ufm.json
- csm_big_data/elasticsearch/mappings/templates/cast-csm-dimm-env.json
- csm_big_data/elasticsearch/mappings/templates/cast-csm-gpu-counters.json
- csm_big_data/elasticsearch/mappings/templates/cast-csm-gpu-env.json
- csm_big_data/elasticsearch/mappings/templates/cast-csm-node-env.json
- csm_big_data/elasticsearch/mappings/templates/cast-csm-processor-env.json
- csm_big_data/elasticsearch/mappings/templates/cast-db-csm.json
- csm_big_data/elasticsearch/mappings/templates/cast-log-console.json
- csm_big_data/elasticsearch/mappings/templates/cast.json
In dynamic_date_formats "strict_date_optional_time" needs to be a
separate comma-separated option, not or'ed with the date time patterns.
Fixes #547
> Fix dynamic_date_formats bug in elasticsearch templates

- csmnet/src/CPP/endpoint_unix.cc
Solves hard to debug situation caused by unprivileged user calling privileged APIs. Daemon immediately returns EPERM but logs show regular send/recv sequence at info-level logging.
This PR adds a warning message indicating that this user has no permission.
> csm: print warning in daemon log when api call is not permitted

- csmd/src/daemon/src/csmi_request_handler/helpers/cgroup.cc
- csmd/src/daemon/src/csmi_request_handler/helpers/cgroup.h
Stopping the IRQ daemon was crashing CSM silently. Replaced the old exec with a nohupped operation to stop the daemon. 
Should now successfully stop the IRQBalance Daemon when `jitter_mitigation.irq_affinity` is set to true.
> IRQ Daemon Fix

- csmd/src/daemon/src/csm_daemon.cc
@pdlun92 found a problem with the CSM daemon exiting non-gracefully in case of database schema version mismatches.
This PR fixes the problem and makes the daemon shut down nicely with an error code.
> csmd: handle db version mismatch exception and exit properly

- csm_big_data/beats/CMakeLists.txt
- csm_big_data/beats/utility-scripts/csmTransactionRebuild.py
- csm_big_data/setupRPM.cmake
- csmdb/sql/CMakeLists.txt
- csmutil/csm_log_utility/CMakeLists.txt
- csmutil/csm_log_utility/Helper_Files/CMakeLists.txt
- csmutil/csm_log_utility/Logs/CMakeLists.txt
- csmutil/csm_log_utility/Reports/CMakeLists.txt
- docs/source/cast-big-data/python-guide.rst
Fixing the missing dependencies outlined in issue #348 added `python-psycopg2` and `python-elasticsearch` to the `csm-bds` and `csm-db`  rpms.
Added a new script `csmTransactionRebuild.py` based on a request by @morrone . This script is described in `docs/source/cast-big-data/python-guide.rst` and located at `csm_big_data/beats/utility-scripts/csmTransactionRebuild.py`. 
The core intention of the script is to rebuild the csm transactional logs from scratch using database queries. It should only be run once in the transition from `1.4.0` to `1.5.0`.
> Adding RPM dependencies and new script for rebuilding transaction data

- csmi/python_samples/node_attributes_query_with_xcat.py
- docs/source/csm-apis/csm_python_guide.md
We want to be able to use an xCAT noderange or nodegroup with CSM APIs.
This approach uses the python wrapper for CSM APIs. By writing a python script we can first call xCAT python restful APIs to get the nodes in a node range, then save that and pass it into the input of a CSM API, such as `node attributes query`. 
This pull request includes :
- an example of how to use xCAT restful python APIs and CSM python APIs to use an xCAT noderange
- An update to the FAQ section of CSM python APIs read the docs to include a note about utf8 encoding. 
1. Nothing to new to test. This pull request add in an example python script of how to use an xCAT node range. not meant to be used in production.
2. Example works and has been tested.
original issue: https://github.com/IBM/CAST/issues/222
> an example of how to use xCAT restful python APIs and CSM python APIs to use an xCAT noderange

- csmd/src/daemon/src/csmi_request_handler/CSMIAllocationAgentUpdateState.cc
Removing the entry from the activelist no longer triggers warning messages on allocation delete.
> Activelist Warning Rework

- csmconf/csm_compute.cfg
- csmd/setupRPM.cmake
- csmd/src/daemon/include/bucket_item_type_definitions.h
- csmd/src/daemon/include/csm_event_routing.h
- csmd/src/daemon/src/CMakeLists.txt
- csmd/src/daemon/src/csm_event_routing_master.cc
- csmd/src/daemon/src/csmi_request_handler/InvGetNodeInventory.cc
- csmd/src/daemon/src/csmi_request_handler/InvSsdWearUpdate.cc
- csmd/src/daemon/src/csmi_request_handler/InvSsdWearUpdate.h
- csmd/src/daemon/src/csmi_request_handler/csm_environmental_handler.cc
- csmd/src/daemon/src/csmi_request_handler/csm_environmental_handler.h
- csmd/src/inv/include/inv_ssd_inventory.h
- csmd/src/inv/include/inv_ssd_wear_serialization.h
- csmd/src/inv/src/CMakeLists.txt
- csmd/src/inv/src/inv_ssd_inventory.cc
- csmd/src/inv/src/inv_ssd_wear_serialization.cc
- csmi/src/common/include/csmi_cmds_def.h
- csmi/src/inv/include/inv_types.h
This pull request contains several new features related to SSD wear collection.
**Summary**
CSM Compute daemons will now start collecting wear_lifespan_used, wear_percent_spares_remaining, wear_total_bytes_written, and wear_total_bytes_read in the csm_ssd table.
These fields will be collected as part of inventory collection whenever a CSM compute daemon starts.
They will also be recollected periodically as part of the "ssd" bucket, which has a configurable frequency in the csm_compute.cfg file.
**Dependancies**
The nvme-cli rpm must be installed on any nodes where SSD wear is intended to be collected.
The ssd configuration section must be added to the "data_collection.buckets" section of the csm_compute.cfg to enable periodic recollection:
```
"data_collection" :
{
"buckets":
[
{ …
```
> Adding SSD wear collection to CSM

- csmd/src/daemon/etc/csmd-compute.service
Adds  LimitMEMLOCK=infinity to the compute service.
> Temporary fix for Issue #62 for CSM 1.5.0

- csmd/src/daemon/src/csmi_request_handler/csm_environmental_handler.cc
- csmd/src/inv/include/inv_ssd_inventory.h
- csmd/src/inv/src/inv_ssd_inventory.cc
- Modified SSD inventory collection to support verbose and quiet levels of trace as requested by the caller.
- Updated the trace messages created during processing of CSM buckets.
With the default trace levels enabled, one trace entry will be created for each bucket item that is processed successfully.
```
[COMPUTE]2019-02-20 12:25:13.001705     csmenv::info     | CSM_ENVIRONMENTAL gpu: GPU data collection was successful.
[COMPUTE]2019-02-20 12:25:13.009847     csmenv::info     | CSM_ENVIRONMENTAL environmental: node environmental data collection was successful.
[COMPUTE]2019-02-20 12:25:13.014682     csmenv::info     | CSM_ENVIRONMENTAL ssd: SSD wear collection was successful.
```
> Updated tracing in CSM buckets

- csmd/src/daemon/src/csmi_request_handler/helpers/cgroup.cc
Fixing a bug where the SMT clamp was lost.
> smt mode should clamp again in cgroup creation.

- docs/source/cast-big-data/python-guide.rst
- docs/source/csmd/csmd_config.rst
Two small documentation updates:
- Fixed a markup typo I noticed:
`python-guide.rst:344: WARNING: Unknown directive type "code-black".`
- Added documentation for the ssd bucket to the csmd_config data_collection section.
> CSM documentation update for SSD wear bucket

- csmd/setupRPM.cmake
- csmutil/csm_log_utility/CMakeLists.txt
- csmutil/csm_log_utility/Logs/CMakeLists.txt
```
ibm-csm-tools-1.6.0-2141.ppc64le.rpm
ibm-csm-tools-1.6.0-2146.noarch.rpm
```
```
numpy
error: Failed dependencies:
numpy is needed by ibm-csm-tools-1.6.0-2143.noarch
Preparing...                          ################################# [100%]
Updating / installing...
1:ibm-csm-tools-1.6.0-2143         ################################# [100%]
```
```
/opt/ibm/csm/tools/Logs/Compute/ReadMe.md
/opt/ibm/csm/tools/Logs/Master/ReadMe.md
/opt/ibm/csm/tools/Logs/Utility/ReadMe.md
/opt/ibm/csm/tools/Logs/Aggregator/ReadMe.md
/opt/ibm/csm/tools/ReadMe.md
/opt/ibm/csm/tools/Logs/Aggregator/ReadMe.md
/opt/ibm/csm/tools/Logs/Compute/ReadMe.md
/opt/ibm/csm/tools/Logs/Master/ReadMe.md
/opt/ibm/csm/tools/Logs/Utility/ReadMe.md
/opt/ibm/csm/tools/ReadMe.md
```
> Packaging updates related to ibm-csm-tools rpm

- bb/src/bbapi2.cc
- bb/tests/src/test_GetUsage.c
Fix issue [IBM/CAST] BB gitcommit version mismatch message displayed via libbbapi (#596)
Version check is now done after setting up logging facility.
Issue 596 discovery.
Future versions of libbbAPI.so will print the git version mismatch only if logging is appropriately set up.
> Issue #596 Enable logs before version check to avoid git commit msg

- csm_big_data/python/CMakeLists.txt
- csm_big_data/python/requirements.txt
- csm_big_data/setupRPM.cmake
- docs/source/cast-big-data/python-guide.rst
The python-elasticsearch dependency was erroneously added. The version present in the rhels 7.5 epel is far too old for the BDS offering. A requirements.txt file will now be provided with the CSM BDS usecases to handle dependencies.
> Removing python-elasticsearch dependency

- csmi/include/struct_generator/rb_tree.pl
- csmi/src/bb/src/csmi_bb_internal.c
- csmi/src/diag/src/csmi_diag_internal.c
- csmi/src/inv/src/csmi_inv_internal.c
- csmi/src/ras/src/csmi_ras_internal.c
- csmi/src/wm/src/csmi_wm_internal.c
To repair a bug in the serialization engine for CSM json.
Fix was applied to the static code generation. The Red Black Tree serialization was fixed to process children of inner leaves (see #610 for more details).
Issue #610 
The transaction log for csm_allocation_create needs the following fields:
```
allocation_id,begin_time,primary_job_id,secondary_job_id,ssd_file_system_name,
launch_node_name,user_flags,system_flags,ssd_min,ssd_max,num_nodes,num_processors,num_gpus,
projected_memory,state,type,job_type,user_name,user_id,user_group_id,user_script,account,
comment,job_name,job_submit_time,queue,requeue,time_limit,wc_key,isolated_cores,compute_nodes
```
> Fixing the serialization of the Red-Black Tree for json serialization.

- bb/scripts/bbtools.pm
- bb/scripts/stageout_admin.pl
Problem:
When a failure during stage out (injected error in these cases), the stage out fails (as expected) but that error is not percolated back to the user.
Provide status of stageout to bhist.
> Fix:  Report to bhist status of stageout

- csmd/src/daemon/include/csm_jitter_info.h
- csmd/src/daemon/src/csm_daemon_config.cc
- csmd/src/daemon/src/csmi_request_handler/helpers/cgroup.cc
- docs/source/csmd/csmd_config.rst
New mechanism set through config file:
`blink_enable : false|true`
Regression path may reuse old tests, but with new flag added.
> Implemented a new mechanism for disabling core blinking

- csmd/src/daemon/src/csmi_request_handler/helpers/cgroup.cc
The off by one error caused the last thread in a core to be blinked when blinking was disabled.
> Fixed off by one error that broke blink disable in cgroup.

- csmd/setupRPM.cmake
- csmdb/sql/CMakeLists.txt
Python dependency (add appropriate dependencies to the CSM rpms so yum can automatically install all of the right packages.)
> csmdb_python_dependency

- csmd/src/daemon/src/csmi_request_handler/helpers/cgroup.cc
- csmd/src/daemon/src/csmi_request_handler/helpers/cgroup.h
Core blinking now follows a deterministic algorithm which selects a behavior to reduce the number of cores blinked. The basic description of the algorithm is as follows:
> Let **X** be the previous core isolation.
> Let **Y** be the next core isolation.
> Then perform a blink operation when
> `X > Y OR ( X == 0 AND Y != 0 )`
The algorithm will then return different values  based on the evaluation of the above algorithm.
* **-1** : When the allocation cgroup cores should be blinked.
* Occurs when `X == 0 AND Y != 0` (When going from no isolation to core isolation).
* **0** : Perform no blink operations.
* Occurs when `X==Y` and `X<Y`.
* Effectively means the set of cores isolated before is a subset of the cores isolated in the new job.
* **>0** : Perform a blink operation on the cores …
> Algorithmic Core Blinking

- csmd/src/pamd/src/csm_pam.cc
- csmutil/src/csmutil_logging.c
The debug level `off` is incorrectly named in the context of the logging utility. Setting the logging level to `disabled`.
New library retested and no output was found.
> Fixing debug level for PAM scripts

- csmd/rpmscripts/csmd.post.uninstall
Added a check of the input variable to the `%postun` scriptlet. Removal does not occur in upgrade as seen in issue # #640.
> Fixed the post install to only trigger when uninstalls are run.

- export_layout/src/preuninstall.sh
Handles uninstall of export layout rpm and upgrade.
Previously, upgrade removed export_layout module.
This will require two successive RPM installs--first with previous export_layout RPM removed.  The second RPM install will work for rpm -U.
> Check in preuninstall whether upgrade or delete of export_layout

- csmtest/buckets/advanced/allocation_timing.py
Wrote a new bucket (utilizing python libraries) to generate timing data for `csm_allocation_create` calls with specified numbers of isolated cores.  As it stands now, the sequence is to create allocations with `0, 0, 1, 0, 1, 2, 1, 0` to stimulate different conditions of the smart core-blinking algorithm.  
Here is a sample output file
```
Allocation: 272 (isolated_cores = 0)
Create time: 0.077843
Allocation: 273 (isolated_cores = 0)
Create time: 0.075625
Allocation: 274 (isolated_cores = 1)
Create time: 12.136847
Allocation: 275 (isolated_cores = 0)
Create time: 1.355861
Allocation: 276 (isolated_cores = 1)
Create time: 10.705613
Allocation: 277 (isolated_cores = 2)
Create time: 0.081201
Allocation: 278 (isolated_cores = 1)
Create time: 1.452159
Allocation: 279 (isolated_cores = 0) …
```
> CSM FVT: Allocation Timing mechanism

- bb/tests/resiliency/connect.robot
Testcases were doing getserver as a user during setup.
> Fix connection open/close testcases

- bb/scripts/nvmfConnect.sh
- bb/src/serial.cc
The NVMe key was set via putenv to the connection script, which caused problems when multiple threads were concurrently handling sayHello requests from multiple compute nodes.
> Fix multithread issue w/ putenv during proxy hello

- csmd/src/daemon/src/csmi_request_handler/csmi_base.h
This PR fixes a problem with timeout responses caused by checking for the wrong event type.
To test run:
```
error_inject -t 5
```
old behavior:
* causes the master daemon to segfault.
* request times out after ~30-35 seconds
new behavior:
* master daemon stays alive
* request returns after 5s
Setting Sev2 because it seems the function that causes this problem is only used by tests like infrastructure_health_check or the above error_inject.
That said, running the infrastructure health test on a system with some failed compute nodes would cause daemons to segfault too. If you feel this is worth a Sev1, please bump up the severity.
> csm: fixing event type check for timeout responses

- bb/scripts/bbtools.pm
- bb/scripts/stagein_admin.pl
- bb/src/bberror.h
- bb/src/nodecontroller_csm.cc
Summary count of success/fails/no responses in bberror.  LV cleanup now occurs when any nodes report success.
> Issue 674: improve error path during partial create failure

- csmd/dcgm.cmake
- csmd/src/inv/include/inv_dcgm_access.h
- csmd/src/inv/src/inv_dcgm_access.cc
This pull request primarily contains a workaround needed to handle changes in DCGM structure definitions that broke backward compatibility (associated NV issue: https://partners.nvidia.com/bug/viewbug/2560401).
Selected comments from the issue above:
```
I think this is the problem:
CSM calls dcgmGetLatestValuesForFields() like this:
dcgmReturn_t rc(DCGM_ST_OK);
dcgmFieldValue_t csm_environmental_field_values[CSM_ENVIRONMENTAL_FIELD_COUNT];
// scan the gpus
for (int i = 0; i < dcgm_gpu_count; i++)
{
rc = (*dcgmGetLatestValuesForFields_ptr)(dcgm_handle, gpu_ids[i], CSM_ENVIRONMENTAL_FIELDS, CSM_ENVIRONMENTAL_FIELD_COUNT, csm_environmental_field_values);
...
}
Previous versions of DCGM (v1.4.1, for example), contain these relevant definitions:
dcgm_agent.h:
dcgmReturn_t …
```
> CSM updates needed to build against DCGM 1.6.3

- csmd/src/inv/ib_and_switch/include/inv_switch_connector_access.h
- csmd/src/inv/ib_and_switch/src/inv_switch_connector_access.cc
- csmd/src/inv/ib_and_switch/src/standalone_ib_and_switch_collection.cc
We noticed an issue with switch module inventory collection. The issue was that each new set of modules over rode the primary key value of the previous set. Effectively only inserting 1 set of module data into CSM database. This pull request resolves that issue. (to the best of my knowledge. I did some minor testing. It seems to be working as expected on my machine.)
In this pull request I added a `rolling_total_module_counter` which keeps track of how many modules came before. This is used to offset the index when grabbing the module data. I used a rolling counter because there may not be the same number of modules on each switch. We can't offset by the same number for each switch.
*Future approach*: This current approach should be removed when we re-work this process to read in the pure …
> fix module issue?

- bb/scripts/bbtools.pm
LSF sets staging scripts cwd to /tmp.  This change captures the user submission parameters and chdir's to the bsub -cwd setting.
> Issue #509: change cwd before calling user scripts

- csmtest/tools/ci_fvt.sh
- csmtest/tools/complete_fvt.sh
Wrote a first pass at a light weight test suite designed for CI environment.  The problem is that a fully "dockerized" csm environment has limited functionality (due to numerous things, for example: lack of systemctl, no access to inventory dependencies). The solution for now is to create `csmtest/tools/ci_fvt.sh` that mirrors `csmtest/tools/complete_fvt.sh` but with compromised test buckets removed.  `ci_fvt.sh` is intended to be run on pull request creation to provide more immediate feedback, `complete_fvt.sh` is intended to be run on baremetal systems (daily and as needed)
For first pass, removed the section that rely heavily on csm infrastructure manipulation and access to inventory modules.  List of removed buckets: 
- basic/hcdiag
- basic/switch_inventory
- …
> CSM FVT Test Suite script for CI

- csmd/src/inv/ib_and_switch/src/inv_ib_connector_access.cc
- working on https://github.com/IBM/CAST/issues/682
Address issues in https://github.com/IBM/CAST/issues/682
I believe that UFM restAPIs changed the output of a missing serial number in the most recent update. Previously we searched for `NA` now it displays as `N/A`. We now look for both forms in our code. 
**Future:** We need to add in more tests to regression: https://github.com/IBM/CAST/issues/686
@thanh-lam opened https://github.com/IBM/CAST/issues/682
1. Have a cable with a `N/A` serial number.
2. run inventory on master, this cable will get put into the CSM database.
3. checkout this branch
4. Have a cable with a `N/A` serial number.
5. run inventory on this branch, this cable will not get put into the CSM database. instead get placed …
> add in search of 'N/A'

- csm_big_data/beats/config/filebeat.yml
- csmdb/sql/csm_db_history_archive.py
- csmdb/sql/csm_db_rollup.py
A Fix for the too many JSON file problem.
Implemented a script to consolidate the JSON files.
Added new configuration to filebeat to handle file closures. Implemented `csm_db_rollup.py` to roll old files up into weekly files.
This doesn't fix the files produced or empty files yet. @williammorrison2 Should we switch to a file containing weekly data for the archive?
> Reducing number of json files #679

- bb/src/main.cc
- bb/src/serial.cc
Removed pthread_once of findSerials and placed priming call in mainThread before worker and transfer thread creates.
Unit tested on gssiovm1-hs for good path with existing nvme-over-fabrics devices.  
Unit tested on gssiovm1-hs for bad path of ```chmod a-x /usr/sbin/nvme```
> Do findSerials early and remove pthread_once invocations

- bb/scripts/bb.cfg.in
- bb/scripts/bbactivate.pl
- bb/scripts/nvme.conf
- bb/scripts/nvmet.json
- bb/src/LVLookup.h
- bb/src/fh.cc
- bb/src/lvlookup.cc
- bb/src/serial.cc
- bb/src/xfer.cc
Allow splitting NVMe over Fabrics connections into separate read and write connections.  This potentially permits using different QoS and service levels for read and write paths.
> Enable distinct read and write NVMeoF connections

- bb/tests/keywords_bbcmd.robot
robot may run on different nodes than targets.  The resize testcases were checking for a directory existence on the wrong node.
> Fix resize testcases when running on different node

- csmi/include/struct_generator/c_funct.txt
- csmi/src/bb/src/csmi_bb_serialization.c
- csmi/src/common/src/csmi_common_serial.c
- csmi/src/diag/src/csmi_diag_serialization.c
- csmi/src/inv/src/csmi_inv_serialization.c
- csmi/src/ras/src/csmi_ras_serialization.c
- csmi/src/wm/src/csmi_wm_serialization.c
Fixing a bug in the x-macro for initialization. Version is now checked init code.
> Issue #776: Version wasn't checked in init code. Version now clamps.

- bb/src/bbproxy.cc
Remove map:at exception for measured values SyncCount and SyncTime
> Tolerate non-existing SyncCount, SyncTime in message

- csm_big_data/beats/config/filebeat.yml
- csm_big_data/logstash/patches/csm_logstash_6-8-1_patch.sh
Provide CSM nov release with comatibility for ELK 6.8.1
Discussed with team members and long hours of trial and error testing.
> Csm elk 6 8 1 compatibility

- bb/scripts/BSCFS_start.pl
BSCFS_start change to run the agent in csh or bash remotely by ssh and set the job env correctly.
> BSCFS_start fork change to work in tcsh (csh) and bash shells

- csmd/src/inv/ib_and_switch/include/inv_ib_connector_access.h
- csmd/src/inv/ib_and_switch/include/inv_switch_connector_access.h
- csmd/src/inv/ib_and_switch/src/inv_ib_connector_access.cc
- csmd/src/inv/ib_and_switch/src/inv_switch_connector_access.cc
- docs/source/csm/csm-inventory/Network.rst
- docs/source/csm/tools.rst
This pull request will have CSM's ufm inventory collection tool be more reliable when collection ufm inventory by being more versatile on how it connects to the ufm daemon.
- hours of debugging and configuration testing. 
- online research
- discussion with Mellanox team
https://github.ibm.com/CORAL/bluecoral/issues/1030
- manual testing
- new code works with both http and https protocols in the `gv.cfg` file for ufmd
- advanced FVT testing has been discussed with @williammorrison2. It may be implemented in Q2 of 2020.
- read the docs for CSM has been updated to include a FAQ about missing serial numbers and communication issues, along with notes on how to debug and configure. 
Sometimes CSM can detect a switch in your system that is incomplete. It is missing a serial number, which CSM …
> CSM Error: "CONNECTOR_ACCESS failed" - 400, 403 - https and http issue in Mellanox 'gv.cfg' file - found by Than - UFM

- bb/src/fh.cc
Handle case after fixup where the remaining length is zero for doing extents.
> For page fixup in fh.cc, if remaining length is 0, do not add extent

- csmdb/sql/csm_db_script.sh
- csmi/src/wm/cmd/allocation_query_details.c
- hcdiag/samples/gpu-health/CMakeLists.txt
Found and fixed some additional problems related to release builds (`--type=Release`).
```
scripts/configure.pl --type=Release --mincmake=3.6 --rpmbuild --parallel
scripts/rebuild noinstall package
```
**1.) csm_db_script.sh is shipped without execute permission**
During build:
`*** WARNING: ./opt/ibm/csm/db/csm_db_script.sh is executable but has empty or no shebang, removing executable bit`
After install:
`/opt/ibm/csm/db/csm_db_script.sh: Permission denied`
Fixed by adding `#!/bin/bash` to the top of the script.
**2.) hcdiag makefile is incorrectly shipped with execute permission**
`*** WARNING: ./opt/ibm/csm/hcdiag/samples/gpu-health/makefile is executable but has empty or no shebang, removing executable bit`
Fixed by making the makefile non-executable.
make still works as expected: …
> Additional fixes related to building with --type=Release

- CMakeLists.txt
- csm_big_data/setupRPM.cmake
- csmd/setupRPM.cmake
RHEL8 changes in csmd switched python-psycopg2 to python2-psycopg2, which breaks RHEL7 installs.  This change detects the build system and selects the right RPM require.
> Fix RHEL7 install break

- csmd/src/inv/ib_and_switch/src/inv_ib_connector_access.cc
- csmd/src/inv/ib_and_switch/src/inv_switch_connector_access.cc
The CSM FVT team found an unhandled exception in the standalone inv collection tool after upgrading to RH8. This exception broke the pipeline of getting inventory data from Mellanox devices into the CSM database. The purpose of this pull request is to restore the pipeline of getting the inv data into the CSM database. 
- We did basic testing and investigation
- googling
- trial and error testing
- code review
- documentation of next/future steps
https://github.ibm.com/CSM/team_process/issues/70
Run tthe CSM ib inventory collection tool on a RH8 machine. 
Example of tool working again:
```
[root@c650f99p06 sbin]# ./standalone_ib_and_switch_collection -c /etc/ibm/csm/csm_master.cfg
UFM reported 133 IB records.
This report from UFM can be found in 'ufm_ib_cable_output_file.json' located at …
```
> CSM Mellanox Inventory Collection - Unhandled Exception

- bb/src/connections.cc
Minor bug:  Handle bad return code from implied SSL_write in SSL authenticate method.
> Coverity 348587 Handle bad RC from SSL_write in authenticate

- bb/src/nodecontroller_csm.cc
- bb/src/nodecontroller_csm.h
Coverity pointed out that the dlopen open handle was leaked storage.  Moved the handle to be in the class, initialized to NULL on class construction, set on dl_open processing, and then dlclose of the handle in the destructor.  Basically, did the good practice coding.
> Handle cleanup of dlopen handle via dlclose/destructor Coverity 357895

- csmtest/include/hcdiag/clustconf.yaml
After upgrading the CSM FVT regression environment to RHEL 8.1, the following test case failure was discovered:
```
Test Case 26: chk-os:                                                                                  FAILED
```
More detailed data:
```
Test Case 26: chk-os
Health Check Diagnostics version 1.8.0, running on Linux 4.18.0-147.5.1.el8_1.ppc64le, c650f99p06 machine.
Using configuration file /opt/ibm/csm/hcdiag/etc/hcdiag.properties.
Using tests configuration file /opt/ibm/csm/hcdiag/etc/test.properties.
Health Check Diagnostics, run id 200429180610388094, initializing...
Validating command argument test.
Validating command argument target.
Allocation request successful, id= 71
Preparing to run chk-os.
Executable: /opt/ibm/csm/hcdiag/tests/chk-os/chk-os.sh exists on remote …
```
> Updated csmtest hcdiag clustconf.yaml template for RHEL 8.1 testing

- csmi/src/CMakeLists.txt
- csmtest/buckets/basic/fvt_allocation_create_and_delete.py
- csmtest/buckets/basic/fvt_node_attributes_query_and_update.py
CSM provides CSM API python libraries implemented via boost-python. This pull request contains changes needed to fix regressions in the CSM API python libraries on RHEL 8 caused by changes in the underlying boost and python packages shipped on RHEL 8. This PR also maintains the ability to build CSM on RHEL7.
On RHEL 7, the CSM API python libraries require python2 (due to underlying dependencies).
On RHEL 8, the CSM API python libraries require python3 (due to underlying dependencies).
Note: see the changes to the CSM FVT scripts contained in this PR for a solution for detecting whether to invoke python2 or python3.
**RHEL7 CSM API python libraries**
_Build environment requirements_
```
cast-boost-python-1.60.0-4.el7a.ppc64le
cast-boost-devel-1.60.0-4.el7a.ppc64le
Python 2.7.5
```
_Runtime …
> Add RHEL 8 csm-api python library support

- csmnet/src/CPP/endpoint_ptp.h
- csmnet/src/CPP/endpoint_ptp_sec.cc
- csmnet/src/CPP/endpoint_ptp_sec.h
- csmnet/src/CPP/multi_endpoint.cc
With the move to RH8, SSL coms for csm daemons wasn't working. This pull request and code change fixes SSL coms for CSM daemons. 
https://github.ibm.com/CSM/team_process/issues/71
testing is described in https://github.ibm.com/CSM/team_process/issues/71
results of testing and code screenshots are in https://github.ibm.com/CSM/team_process/issues/71
> Csm ssl coms

- csmi/src/diag/cmd/diag_run_end.c
- csmi/src/diag/src/csmi_diag_run_end.c
one of the diag test cases failed. it pointed to a fault in the daig run end api. after investigation we concluded that diag run api was not working correctly. this pull requests fixes the issue with diag run end. 
A struct was not properly initialized during an early phase of the api. This was not detected. got past a few levels into the api guts. and eventually caused a null buffer, which was causing the api to fail serialization and data packing. the issue was resolved and the struct was initialized.  
https://github.ibm.com/CSM/team_process/issues/80
after the patch was applied
1. I ran a successful diag run end from the cmd line (could not do before)
2. I reproduced the original error case and then re ran and passed
Before:
```
[root@c650f99p06 csmtest]# …
```
> Team process 80

- bb/src/bbproxy.cc
- export_layout/src/export_layout.c
export_layout is now marked in use when /dev/export_layout is opened.  If export_layout was removed after an open against /dev/export_layout, the close (release) would OOPs.  Other OOPs situations were possible.  The use count is incremented on open and decrement on release.
bbproxy was changed to do a dummy action of open export_layout early to seize it so it could not be removed.  If /dev/export_layout could not be opened, bbproxy quits on the early discovery.
> Fix rmmod export_layout OOPs when in use by bbproxy

- hcdiag/src/tests/chk-sys-firmware/chk-sys-firmware.pm
- working on https://github.ibm.com/CSM/team_process/issues/81
RHEL8.1FVT hcdiag Test Case 23: chk-sys-firmware was failing due to perl error. This pull request resolves that error on RH8. 
I believe the core issue was "keys" wasn't getting the input it was expecting. `sort(keys($errNodes))` is one of the 2 examples. we ended up de referencing the variable. `sort(keys(%$errNodes))` which resolved the issue on RH8. research, explainations, and thought process can be found in the main issue.
more details and the thought process can be found here: https://github.ibm.com/CSM/team_process/issues/81
see: https://github.ibm.com/CSM/team_process/issues/81
https://github.ibm.com/CSM/team_process/issues/81
- I re ran `buckets/basic/hcdiag.sh ` on RH8. and no longer saw the issues and logs @besawn …
> team process 81

- csmconf/csm_api.cfg
- csmtest/include/prologs/privileged_epilog_timeout
- csmtest/include/prologs/privileged_prolog_timeout
The previous default values in csm_api.cfg can sometimes lead to premature timeouts in some situations. This PR increases the default timeouts of several CSM APIs to safer default values. 
These values may still require tuning in a production system based on cluster specific timings.
For example, worst case times for prolog and epilog script completion need to be factored in to the overall csm_allocation_create, csm_allocation_delete, and csm_allocation_update_state timeouts.
After adjusting the time out values, two FVT test cases failed due to sleeping for an insufficient length of time to trigger the csm_allocation_create and csm_allocation_delete time outs:
```
/test/results/buckets/error_injection/allocation.log:Test Case 6: csm_allocation_create prolog error timeout: …
```
> Updated csm_api.cfg file to contain more appropriate default values

- csmd/dcgm.cmake
- csmd/src/inv/src/inv_dcgm_access.cc
- csmtest/buckets/advanced/allocation_timing.py
- hcdiag/src/tests/common/functions
This PR contains several small changes related to regression testing with datacenter-cpu-manager 2.0.
- Modified the REQUIRED_DCGM_VERSION to allow building against any installed version of DCGM.
- Removed references to the utility function errorString() provided by DCGM due to a change in the function signature between DCGM 1.X and 2.X that makes maintaining compatibility difficult.
- Updated the CSM FVT allocation_timing.py script so it will run with either python2 or python3, using whichever version is installed.
- Added a few additional models to the hcdiag supported models.
> CSM updates related to DCGM 2.0.4-1 regression testing

- bb/fvt-ansible/csmStart.yml
Copy nodelist from localhost /tmp/nodelist to /tmp/nodelist-csm on management node and then parse out csv list of nodes
> Fix management node compute list for node availability

- CMakeLists.txt
Changes in the GA version of NVIDIA datacenter-gpu-manager-2.0.10-1 require CSM 1.8.0 to be rebuilt against the updated header files in included in datacenter-gpu-manager-2.0.10-1 for successful integration of the two products.
This pull request bumps the CAST rpm version number to prepare for the rebuild.
Note: The DCGM rpm name is `datacenter-gpu-manager-2.0.10-1`, but it reports the version number as `datacenter-gpu-manager-2.0.8-1` via rpm commands once it is installed.
> Bump version number to 1.8.1 to prepare to rebuild with datacenter-gpu-manager-2.0.10-1

- csmi/src/wm/cmd/allocation_step_end.c
While testing the release build of CSM 1.8.1, the following problem was discovered via CSM FVT regression test:
```
/test/results/buckets/basic/step.log:Test Case 5:  Calling csm_allocation_step_end                  (allocation_id: 4 step_id: 1):          FAILED
/test/results/buckets/basic/step_tmp.log:(null) FAILED: errcode: 28 errmsg: Message packing error
```
The problem only occurs when building the release rpms using the following process on RHEL 8.X:
`scripts/configure.pl --type=Release --mincmake=3.6 --rpmbuild --parallel; scripts/rebuild noinstall package`
and does not reproduce when building without the `--type=Release` flag:
`scripts/configure.pl --mincmake=3.6 --rpmbuild --parallel; scripts/rebuild noinstall package`
This problem is due to allocation_step_end.c failing to …
> Added csm_init_struct to csm_allocation_step_end to fix Message packing error after building with --type=Release

- csmd/src/inv/src/inv_gpu_inventory.cc
When building CSM on RHEL 8, the following warnings are reported that are not reported when building on RHEL 7:
```
/u/besawn/github/CAST.besawn.RHEL8/csmd/src/inv/src/inv_gpu_inventory.cc:157:16: warning: \u2018char* strncpy(char*, const char*, size_t)\u2019 specified bound 32 equals destination size [-Wstringop-truncation]
/u/besawn/github/CAST.besawn.RHEL8/csmd/src/inv/src/inv_gpu_inventory.cc:160:16: warning: \u2018char* strncpy(char*, const char*, size_t)\u2019 specified bound 32 equals destination size [-Wstringop-truncation]
/u/besawn/github/CAST.besawn.RHEL8/csmd/src/inv/src/inv_gpu_inventory.cc:163:16: warning: \u2018char* strncpy(char*, const char*, size_t)\u2019 specified bound 32 equals destination size [-Wstringop-truncation] …
```
> CSM RHEL8: fix GCC strncpy warnings [-Wstringop-truncation] in CSM GPU inventory

- csmd/src/inv/src/inv_dcgm_access.cc
This PR addresses the issues described in issue #953.
The first change is related to the DCGM library name CSM uses when attempting to dynamically load libdcgm.so.
DCGM has used different library naming conventions with different releases. In order to try to maintain compatibility with as many versions of DCGM as possible, we try to load the library using the most current library names first and fall back to the oldest library name last. If we succeed in loading the library using any of the names, everything should function normally. If we fail to load using any library name, continue to log a warning message.
```
[root@c650f99p36 ~]# rpm -q datacenter-gpu-manager
datacenter-gpu-manager-2.0.10-1.ppc64le
[root@c650f99p36 ~]# ls -al /usr/lib64/libdcgm.so*
lrwxrwxrwx 1 root root      12 Jul …
```
> Fix CSM log warning messages related to transitioning to DCGM 2.X from 1.X

- csmd/rpmscripts/csmd.post.install
This PR addresses https://github.com/IBM/CAST/issues/946 by altering the suggested order of these two lines in `/etc/pam.d/sshd`:
```
#session    required     libcsmpam.so
session    include      postlogin
```
Prior to this change, the `ibm-csm-core` rpm postinstall script was inserting the libcsmpam.so lines into `/etc/pam.d/sshd` like this:
```
#%PAM-1.0
auth       substack     password-auth
auth       include      postlogin
account    required     pam_sepermit.so
account    required     pam_nologin.so
#account    required     libcsmpam.so
account    include      password-auth
password   include      password-auth
session    required     pam_selinux.so close
session    required     pam_loginuid.so
session    required     pam_selinux.so open env_params
session    required …
```
> CSM RHEL 8: updated rpm install script to change ordering of libcsmpam.so session entry in /etc/pam.d/sshd

- csmd/setupRPM.cmake
Several tests included with hcdiags require perl-YAML, add the required package to the ibm-csm-hcdiag rpm to improve the package installation experience.
Prior to this change, there are several hcdiags test cases that fail in the CSM FVT bucket with a similar error message. The failed tests include:
```
[root@c650f99p06 csmtest]# grep FAIL /test/results/buckets/basic/hcdiag.log 
Test Case 16: chk-temp:                                                                                FAILED
Test Case 21: chk-cpu:                                                                                 FAILED
Test Case 22: chk-cpu-count:                                                                           FAILED
Test Case 23: chk-sys-firmware: …
```
> Added missing rpm dependency on perl-YAML to ibm-csm-hcdiag rpm

- CMakeLists.txt
Bump the rpm version number in the master branch to 1.8.2 in preparation for the upcoming release. 
Note: we may merge `master` into the `cast_1_8_x ` branch prior to generating any final build for this release.
> Updated CAST RPM version numbers to 1.8.2

- csmtest/buckets/basic/bb.sh
_To fix an issue related to a test case which was calling `csm_bb_vg_create`_
The issue was that the "hard coded" s/n value was using "ssd_01" instead of the s/n collected during inventory. This was carried over from the previous update I made on `Test Case 1: Checking ssd data in the csmdb`
Run the bb.sh bucket again
```
------------------------------------------------------------
Starting BB API Bucket
------------------------------------------------------------
Thu Sep 10 15:40:25 EDT 2020
------------------------------------------------------------
[2020-09-10 15:40:25.2194] Test Case 1: Checking ssd data in the csmdb if already populated from the inventory collection:                    PASS
[2020-09-10 15:40:25.4157] Test Case 2: Calling csm_bb_vg_create: …
```
> added in an additional check for the s/n while calling csm_bb_vg_create

- bb/scripts/bbactivate.pl
LVM cannot examine NVMf block devices for remote logical volumes.
> Update RHEL8 default lvm.conf global_filter setting

- scripts/Dockerfile
RHEL7 createrepo on RHEL8 RPMs doesn't quite work.  Putting createrepo inside the build environment.
> Add createrepo to build package list

- csmd/setupRPM.cmake
- csmutil/csm_log_utility/API_Statistics.py
- csmutil/csm_log_utility/CMakeLists.txt
_additional checking needed to install the right python package for the ibm-csm-tool package_
Issue #959 explains the details of specific issue.
1. Run: `yum install ibm-csm-tools-1.8.2-3557.noarch.rpm`
2. Run: `/opt/ibm/csm/tools/API_Statistics.py` (to see if the script is working as expected)
3. Run some tests to populate statistical information
a. `/csm_allocation_query_active_all`
b. `/csm_cluster_query_state`
```
[root@c650f99p06 bin]# ./csm_cluster_query_state
---
...
```
```
[root@c650f99p06 tools]# ../bin/csm_allocation_query_active_all
---
num_allocations: 0
...
[root@c650f99p06 tools]# ../bin/csm_allocation_query_active_all
---
num_allocations: 0
...
[root@c650f99p06 tools]# ../bin/csm_allocation_query_active_all
--- …
```
> fixed numpy dependency for python2 in ibm-csm-tools rpm

- bb/ansible/certificates.yml
Unit testing was against certificates.yaml with a pause inserted to avoid damaging certificates in place
sudo ansible-playbook -i /u/tgooding/hosts_rhel7 /u/meaho/CAST/bb/ansible/certificates.yml 
(1) Unit tested on p25 for existing directories on servers and computes.  Passed test.
(2) Moved /etc/ibm/ to /etc/ibm2 on p25
/etc/ibm was created with correct permissions and owner/group of root/root
ansible noted a change on p25 "changed: [c650f06p25]" 
Moved /etc/ibm2 back to /etc/ibm to restore environment 
Removed pause in certificates.yaml for running scoped test 
Also set backup to no for replacing certificates and keys.
> Ensure /etc/ibm created on computes and bbserver nodes

- bb/src/nodecontroller_csm.cc
- bb/src/nodecontroller_csm.h
Unit tested that db entry has bb for volume group on IST systems f5n01 and f5n05.
> Do csm init of structures, use local string for config get vg name

- bb/src/bbcmd.cc
- bb/src/nodecontroller.cc
- bb/src/nodecontroller.h
Unit testing on f5n05 and ln01.  Code impacts running of bbcmd on compute node.  
Previous errors of "no data" have gone away.  
Materials from a bsub run are in:
/ESS/gpfst/meaho/workdir/30925
```[0907][meaho@ln01:/ESS/gpfst/meaho/workdir/30925]
$ ls -l
total 70
-rw-r--r-- 1 root  root  6563 Nov 12 20:07 30925-cat.txt
-rw------- 1 meaho meaho 7446 Nov 12 20:04 30925.env
-rw-rw-r-- 1 meaho meaho  167 Nov 12 20:06 30925.err
-rw------- 1 meaho meaho 1207 Nov 12 20:05 30925.log
-rw-rw-r-- 1 meaho meaho 2065 Nov 12 20:06 30925.out
drwxr-xr-x 2 root  root  4096 Nov 13 09:04 bbcmd-fn05
drwxr-xr-x 2 root  root  4096 Nov 13 08:45 bbcmd-ln01
-rw-r--r-- 1 root  root  5024 Nov 13 08:54 bb_stagein-30925.log
-rw-r--r-- 1 root  root  3793 Nov 13 08:54 bb_stageout-30925.log
-rw-rw-r-- 1 meaho meaho 5008 …
```
> Prefer xcat name if available over hostname

- bb/src/fh.cc
Tested and works on IST system with ln01 launch node and compute node f5n05 using a bsub with stage in request.
> Handle mtime conversion conditioned on getstats success

- bb/src/bbcmd.cc
gdb of bbcmd <noargs>
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6e88e94 in __strchr_power7 () from /lib64/libc.so.6
gdb) bt
#0  0x00007ffff6e88e94 in __strchr_power7 () from /lib64/libc.so.6
#1  0x0000000010022d84 in strstr (__needle=0x10066cc0 "^", __haystack=<optimized out>) at /usr/include/string.h:333
#2  main (orig_argc=<optimized out>, orig_argv=0x7ffffffff148) at /u/meaho/CAST/bb/src/bbcmd.cc:1026
CAST/bb/src/bbcmd.cc:1026
if(strstr(argv[1], "^") != NULL)
argv[1] is NULL
> Fix exception bbcmd no arguments at bbcmd.cc:1026 strchr(argv[1]

- bb/src/LVUtils.cc
- bb/src/fh.cc
This fix addresses issue #1003.  Solution is to prevent the add of a duplicate file handle in the registry.
Change to fh.cc has the change to the addFilehandle() method.  Previously, only a value of zero could be returned.  With this change, a -1 can now be returned indicating the duplicate file handle entry.  That -1 will be returned directly for bbProxy.  Due to restart logic, bbServer can actually run into this case when attempting to reuse a transfer definition that was already stored in the metadata.  In that case, we attempt to release the entry that already exists and then insert the new file handle.
There are four locations in the code that invoked addFilehandle(), three in LVUtils.cc and one in xfer.cc.  For LVUtils.cc, one location was adding the source-index to the file handle …
> Fix for issue #1003

- bb/ansible/bbCheck.yml
- bb/ansible/bbInstall.yml
- bb/ansible/bbStart.yml
- bb/ansible/bbUninstall.yml
- bb/ansible/certificates.yml
- bb/ansible/nodelist.yml
- bb/src/bbproxy.cc
- bb/src/connections.cc
- transport/include/CnxSock.h
- transport/src/CnxSock.cc
- transport/src/CnxSockSSL.cc
Tested under bbrobot fvt and now works.
Improved ansible processing for updating burst buffer RPMs.
Track AUTHENTICATE message in logs.
LOG SSL_errror if it occurs on SSL_accept, SSL_connect, etc.
When processing OPEN_SERVER from bbcmd, bbproxy sleeps one second after SSL_connect to give SSL (re)negotiation to complete before sending AUTHENTICATE message to bbserver.  The SSL protocol and the application use the same socket for read/write.  The sleep(1) gives the open SSL protocol engine time to complete any hand shake between bbproxy and bbserver.  
Fix rare exception for a null pointer in connect.cc when a connection object is not returned because connect failed.
> For bbcmd OPEN_SERVER message to bbproxy, fix bbproxy connecting via SSL to named 

- csm_big_data/logstash/CMakeLists.txt
- csm_big_data/logstash/patches/csm_logstash_patch_jruby_9.2.8.sh
- csm_big_data/logstash/plugins/csm_event_correlator/Gemfile
- csm_big_data/logstash/plugins/csm_event_correlator/build.sh
This fixes the dependency/compatibility issues with logstash that we are testing with
`logstash-7.5.1-1_ol001.el8.ppc64le.rpm`
additional prerequisite:
`java-11` is also needed.
Needed dependencies while setting up:
* logstash-codec-plain -v 3.0.6
* jar-dependencies -v 0.4.0
The `csm_big_data/logstash/plugins/csm_event_correlator/build.sh` script would try to pull in the latest versions of
* logstash-codec-plain 3.1.0
* jar-dependencies 0.4.1
This was the error message while trying to install the CSM BDS RPMS `ibm-csm-bds-`, `ibm-csm-bds-logstash-`
```
ERROR: An error occured when installing the: file:///opt/ibm/csm/bigdata/logstash/plugins/logstash-filter-csm-event-correlator.zip, to have more information about the error add a DEBUG=1 before running the command., message: You have …
```
> CSM BDS logstash dependency fixes

- bb/src/usage.cc
Compiled in 8.4 docker, used local tools to create a repo and uninstall/install RPMS and start up daemons.  Ran against robot from Jenkins for testing.
> Skip token of newline in getLocalReadWrite to avoid stoull(newline)

- bb/ansible/bbserverIPlist.yml
- bb/ansible/nodelist.yml
- bb/scripts/bbactivate.pl
- bb/src/serial.cc
Support bbactivate option to override LV volumegroup in the configuration file, and handle NVMf tcp transports
> Add volumegroup and tcp transport options

- csmtest/buckets/basic/hcdiag.sh
- hcdiag/src/tests/chk-ib-pcispeed/chk-ib-pcispeed.sh
This PR contains a fix and testcase enhancement for #1017
I was able to reproduce the problem described in the original issue. I could not reproduce the problem on RHEL 7.6-Alt, it was introduced somewhere between RHEL 7.6-Alt and RHEL 8.4. I validated that the fix works successfully on both RHEL 7.6-Alt and RHEL 8.4.
Unit test of `chk-ib-pcispeed` on RHEL 8.4, before the fix (failure case):
```
[root@c650f99p06 ~]# xdsh c650f99p26 "cat /etc/redhat-release"
c650f99p26: Red Hat Enterprise Linux release 8.4 (Ootpa)
[root@c650f99p06 ~]# /opt/ibm/csm/hcdiag/bin/hcdiag_run.py --target "c650f99p26" --test "chk-ib-pcispeed" 2>&1 | grep chk-ib-pcispeed
Preparing to run chk-ib-pcispeed.
Executable: /opt/ibm/csm/hcdiag/tests/chk-ib-pcispeed/chk-ib-pcispeed.sh exists on remote node(s). …
```
> Fixed hcdiag chk-ib-pcispeed test for RHEL 8.4 #1017
